In [152]:
import pandas as pd
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.feature_selection import VarianceThreshold
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
import numpy as np
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB

In [3]:
train=pd.read_csv('training_data.csv')

In [4]:
train

,id,ad,link,timestamp,checkout,order_placed,grp,funnel_level
0,session446676598812,ad412316860435,link1288490188810,2018-04-30T14:39:22.000-04:00,1,1,grp936302870529,lower
1,session60129542152,ad584115552306,link1288490188810,2018-04-30T08:39:23.000-04:00,1,1,grp936302870529,lower
2,session1511828488251,ad1056561954841,link1288490188810,2018-04-30T17:24:01.000-04:00,1,1,grp936302870529,lower
3,session1142461300754,ad1666447310876,link1288490188810,2018-04-30T10:42:57.000-04:00,1,1,grp936302870529,lower
4,session1142461300754,ad1666447310876,link1288490188810,2018-04-30T10:43:19.000-04:00,1,1,grp936302870529,lower
5,session1314259992659,ad34,link1288490188800,2018-04-30T22:58:04.000-04:00,1,1,grp111669149696,lower
6,session206158430275,ad38,link1288490188800,2018-04-30T16:47:21.000-04:00,1,1,grp111669149696,lower
7,session8589934632,ad14,link1288490188800,2018-04-30T15:57:36.000-04:00,1,1,grp111669149696,lower
8,session523986010167,ad15,link1288490188800,2018-04-30T16:10:54.000-04:00,1,1,grp111669149696,lower
9,session1357209665542,ad58,link1288490188800,2018-04-30T08:19:05.000-04:00,1,1,grp111669149696,lower
10,session1236950581279,ad8589934618,link1288490188800,2018-04-30T14:15:55.000-04:00,1,1,grp111669149696,lower
11,session1546188226610,ad8589934595,link1288490188800,2018-04-30T16:02:51.000-04:00,1,0,grp111669149696,lower
12,session695784701963,ad8589934598,link1288490188800,2018-04-30T13:20:54.000-04:00,1,1,grp111669149696,lower
13,session309237645347,ad17179869208,link1288490188800,2018-04-30T13:02:41.000-04:00,1,1,grp111669149696,lower
14,session858993459270,ad17179869188,link1288490188800,2018-04-30T19:39:19.000-04:00,1,0,grp111669149696,lower
15,session584115552299,ad25769803828,link1288490188800,2018-04-30T14:57:38.000-04:00,1,1,grp111669149696,lower
16,session944892805202,ad25769803781,link1288490188800,2018-04-30T22:54:40.000-04:00,1,1,grp111669149696,lower
17,session695784702028,ad25769803791,link1288490188800,2018-04-30T21:34:55.000-04:00,1,1,grp111669149696,lower
18,session1108101562390,ad34359738435,link1288490188800,2018-04-30T11:35:05.000-04:00,1,1,grp111669149696,lower
19,session755914244140,ad34359738430,link1288490188800,2018-04-30T14:56:47.000-04:00,1,1,grp111669149696,lower
20,session1245540515897,ad34359738407,link1288490188800,2018-04-30T18:32:49.000-04:00,1,1,grp111669149696,lower
21,session25769803819,ad42949672981,link1288490188800,2018-04-30T14:15:04.000-04:00,0,1,grp111669149696,lower
22,session1219770712099,ad51539607565,link1288490188800,2018-04-30T13:28:22.000-04:00,1,1,grp111669149696,lower
23,session919123001364,ad51539607591,link1288490188800,2018-04-30T19:53:57.000-04:00,1,1,grp111669149696,lower
24,session1632087572522,ad51539607555,link1288490188800,2018-04-30T14:26:05.000-04:00,1,1,grp111669149696,lower
25,session1657857376284,ad51539607573,link1288490188800,2018-04-30T11:00:32.000-04:00,1,1,grp111669149696,lower
26,session755914244159,ad51539607599,link1288490188800,2018-04-30T18:14:40.000-04:00,1,1,grp111669149696,lower
27,session1571958030356,ad51539607574,link1288490188800,2018-04-30T14:34:44.000-04:00,1,0,grp111669149696,lower
28,session1589137899580,ad60129542179,link1288490188800,2018-04-30T16:32:30.000-04:00,1,1,grp111669149696,lower
29,session292057776215,ad60129542176,link1288490188800,2018-04-30T22:30:22.000-04:00,1,1,grp111669149696,lower
...,...,...,...,...,...,...,...,...
199380,session1082331758607,ad1400159338542,link1657857376281,2018-04-30T10:21:57.000-04:00,1,0,grp1589137899520,middle
199381,session223338299470,ad1425929142321,link1657857376281,2018-04-30T21:53:46.000-04:00,0,0,grp1589137899520,middle
199382,session1451698946090,ad1511828488250,link1657857376281,2018-04-30T15:36:26.000-04:00,0,0,grp1589137899520,middle
199383,session1434519076883,ad1657857376304,link1657857376281,2018-04-30T10:31:33.000-04:00,1,1,grp1589137899520,middle
199384,session111669149700,ad1700807049247,link1657857376281,2018-04-30T06:24:16.000-04:00,0,0,grp1589137899520,middle
199385,session1589137899603,ad128849018915,link1657857376258,2018-04-30T21:19:48.000-04:00,1,0,grp369367187456,upper
199386,session1108101562426,ad1322849927226,link1657857376258,2018-04-30T18:57:24.000-04:00,0,0,grp369367187456,upper
199387,session1649267441741,ad1683627180052,link1657857376258,2018-04-30T22:06:27.000-04:00,1,0,grp369367187456,upper
199388,session1159641169963,NaN,link1657857376276,2018-04-30T14:04:44.000-04:00,0,0,grp1340029796352,upper
199389,session1176821039157,ad523986010169,link1657857376276,2018-04-30T15:11:58.000-04:00,0,0,grp1340029796352,upper
199390,session1185410973742,NaN,link1657857376271,2018-04-30T16:26:17.000-04:00,0,0,grp1073741824001,upper
199391,session1425929142350,NaN,link1657857376267,2018-04-30T20:46:09.000-04:00,1,0,grp987842478080,upper
199392,session1425929142350,NaN,link1657857376267,2018-04-30T20:46:09.000-04:00,1,0,grp1073741824000,upper
199393,session1477468749836,NaN,link1657857376260,2018-04-30T09:46:33.000-04:00,0,0,grp446676598784,upper
199394,session75,NaN,link1657857376259,2018-04-30T20:56:29.000-04:00,1,0,grp446676598784,upper
199395,session94489280529,NaN,link1657857376259,2018-04-30T11:08:54.000-04:00,1,1,grp446676598784,upper
199396,session481036337183,NaN,link1657857376259,2018-04-30T12:06:56.000-04:00,0,0,grp446676598784,upper
199397,session1194000908300,NaN,link1657857376259,2018-04-30T10:41:50.000-04:00,0,0,grp446676598784,upper
199398,session197568495721,ad25769803803,link1657857376257,2018-04-30T22:03:12.000-04:00,0,0,grp687194767360,upper
199399,session1331439861761,ad266287972383,link1657857376257,2018-04-30T00:53:51.000-04:00,0,0,grp687194767360,upper
199400,session197568495721,ad25769803803,link1657857376257,2018-04-30T22:03:12.000-04:00,0,0,grp343597383680,upper
199401,session1331439861761,ad266287972383,link1657857376257,2018-04-30T00:53:51.000-04:00,0,0,grp343597383680,upper
199402,session94489280609,ad996432412677,link1657857376263,2018-04-30T21:12:27.000-04:00,0,0,grp936302870528,upper
199403,session704374636553,ad919123001358,link1657857376264,2018-04-30T12:50:24.000-04:00,0,0,grp936302870528,upper
199404,session420906795070,ad1563368095799,link1657857376266,2018-04-30T16:57:56.000-04:00,0,0,grp936302870528,upper
199405,session695784701988,NaN,link1657857376273,2018-04-30T13:40:18.000-04:00,0,1,grp1254130450432,upper
199406,session1245540515886,NaN,link1657857376273,2018-04-30T15:20:54.000-04:00,0,0,grp1254130450432,upper
199407,session1348619730991,NaN,link1657857376273,2018-04-30T17:15:26.000-04:00,1,0,grp1254130450432,upper
199408,session412316860455,ad1228360646711,link1657857376273,2018-04-30T14:33:32.000-04:00,0,0,grp1254130450432,upper
199409,session1675037245453,ad1348619730974,link1657857376273,2018-04-30T09:24:21.000-04:00,0,0,grp1254130450432,upper

In [5]:
train_copy=train.copy()

In [6]:
def unique_values(column='abc'):
    df=pd.DataFrame()
    df=train_copy[column].value_counts().reset_index()
    if(len(df)>50):
        df.columns=[column,'count']
        df.to_csv('{}_count.csv'.format(column))
        print(column+'------Generated as csv')
        print(df.head(20))
    else:
        print(column+'unique value')
        print(df)

In [7]:
def missing_data(df):
    df1=df.isna()
    for i in list(df.columns):
#         print(i)
#         print(df1[df1[i]==True])
        a=len(df1[df1[i]==True])
        if(a>0):
            print("the column with missing data",i)
            print("total missing data",len(df[df1[i]==True]))
            df[i]=df[i].fillna('noad')
            print(df)
    return df

In [8]:
def encoding_label(column="abc"):
    if(column!='timestamp' and column!='checkout' and column!='order_placed'):
        try:
            var=0
            var = preprocessing.LabelEncoder()
            var.fit(train_copy[column])
            print(column)
            print(var.classes_)
            train_copy[column]=var.transform(train_copy[column])
            print(train_copy[column])
        except:
            print(column+' not done with label encoding - error')
    else:
        if(column=='timestamp'):
            print("timestamp is skipped")
        elif(column=='checkout'):
            print("checkout is not need")
        elif(column=='order_placed'):
            print("order_placed is not need")

In [9]:
train_copy.nunique()

id              13977
ad              10362
link             5232
timestamp       62697
checkout            2
order_placed        2
grp               108
funnel_level        3
dtype: int64

id_count=pd.DataFrame()
print(len(train_copy['id'].value_counts()))
id_count=train_copy['id'].value_counts().reset_index()
id_count.columns=['id','count']
id_count.to_csv('id_count.csv')

In [10]:
for i in list(train.columns):
    print(i)
    unique_values(i)

id
id------Generated as csv
                      id  count
0    session************    530
1     session51539607562    235
2    session609885356060    187
3   session1683627180067    165
4   session1314259992599    155
5   session1254130450472    150
6   session1451698946113    145
7   session1176821039131    143
8   session1185410973702    143
9    session446676598812    140
10   session292057776210    139
11  session1228360646716    139
12   session609885356058    127
13   session146028888069    123
14  session1357209665554    122
15  session1537598292007    122
16   session274877906977    121
17   session395136991286    120
18     session8589934597    119
19  session1425929142338    118
ad
ad------Generated as csv
                 ad  count
0    ad************    246
1    ad369367187493    229
2    ad326417514499    219
3    ad146028888064    203
4   ad1108101562368    190
5   ad1099511627776    184
6   ad1700807049221    166
7    ad876173328398    160
8    ad730144440337    157
9     ad17179869192    157
10  ad1219770712107    153
11   ad403726925832    151
12   ad807453851657    141
13  ad1382979469357    131
14  ad1236950581260    129
15   ad798863917082    128
16  ad1597727834128    127
17   ad292057776133    124
18   ad412316860435    120
19   ad824633720864    120
link
link------Generated as csv
                 link  count
0    link798863917076  15485
1   link1288490188815  11578
2    link755914244118  10180
3    link532575944722   9617
4    link214748364811   9190
5   link1468878815250   5683
6    link996432412694   3260
7   link1194000908303   2942
8   link1125281431562   2879
9    link257698037775   2681
10   link369367187470   2605
11    link25769803776   2520
12   link627065225236   2293
13  link1030792151065   2293
14  link1288490188816   2070
15   link395136991258   1824
16     link8589934595   1656
17   link824633720850   1566
18  link1683627180045   1561
19    link34359738385   1179
timestamp
timestamp------Generated as csv
                        timestamp  count
0   2018-04-30T16:18:24.000-04:00     19
1   2018-04-30T12:33:50.000-04:00     18
2   2018-04-30T10:57:40.000-04:00     17
3   2018-04-30T16:32:08.000-04:00     17
4   2018-04-30T10:53:32.000-04:00     16
5   2018-04-30T12:21:36.000-04:00     16
6   2018-04-30T21:50:38.000-04:00     16
7   2018-04-30T16:18:35.000-04:00     16
8   2018-04-30T14:00:05.000-04:00     15
9   2018-04-30T14:16:30.000-04:00     15
10  2018-04-30T19:44:40.000-04:00     15
11  2018-04-30T16:25:29.000-04:00     15
12  2018-04-30T18:44:16.000-04:00     15
13  2018-04-30T09:14:28.000-04:00     15
14  2018-04-30T10:21:00.000-04:00     15
15  2018-04-30T14:25:22.000-04:00     15
16  2018-04-30T18:43:57.000-04:00     15
17  2018-04-30T15:15:30.000-04:00     15
18  2018-04-30T08:22:17.000-04:00     15
19  2018-04-30T10:25:47.000-04:00     15
checkout
checkoutunique value
   index  checkout
0      0    116350
1      1     83060
order_placed
order_placedunique value
   index  order_placed
0      0        159896
1      1         39514
grp
grp------Generated as csv
                 grp  count
0   grp1340029796352  93084
1   grp1511828488192  10156
2   grp1056561954816  10057
3    grp936302870528   9093
4    grp489626271744   4253
5   grp1108101562368   4197
6   grp1013612281856   3753
7   grp1589137899520   3509
8    grp644245094400   2725
9    grp377957122048   2676
10   grp670014898176   2522
11   grp257698037760   2418
12   grp111669149696   2094
13   grp936302870529   2087
14   grp687194767360   2051
15  grp1511828488193   2030
16   grp987842478080   1966
17   grp498216206336   1554
18  grp1468878815232   1401
19   grp206158430208   1399
funnel_level
funnel_levelunique value
    index  funnel_level
0   upper        120772
1  middle         58282
2   lower         20356

In [11]:
len(train)

199410

In [12]:
train_copy=missing_data(train)

the column with missing data ad
total missing data 79375
                          id               ad               link  \
0        session446676598812   ad412316860435  link1288490188810
1         session60129542152   ad584115552306  link1288490188810
2       session1511828488251  ad1056561954841  link1288490188810
3       session1142461300754  ad1666447310876  link1288490188810
4       session1142461300754  ad1666447310876  link1288490188810
5       session1314259992659             ad34  link1288490188800
6        session206158430275             ad38  link1288490188800
7          session8589934632             ad14  link1288490188800
8        session523986010167             ad15  link1288490188800
9       session1357209665542             ad58  link1288490188800
10      session1236950581279     ad8589934618  link1288490188800
11      session1546188226610     ad8589934595  link1288490188800
12       session695784701963     ad8589934598  link1288490188800
13       session309237645347    ad17179869208  link1288490188800
14       session858993459270    ad17179869188  link1288490188800
15       session584115552299    ad25769803828  link1288490188800
16       session944892805202    ad25769803781  link1288490188800
17       session695784702028    ad25769803791  link1288490188800
18      session1108101562390    ad34359738435  link1288490188800
19       session755914244140    ad34359738430  link1288490188800
20      session1245540515897    ad34359738407  link1288490188800
21        session25769803819    ad42949672981  link1288490188800
22      session1219770712099    ad51539607565  link1288490188800
23       session919123001364    ad51539607591  link1288490188800
24      session1632087572522    ad51539607555  link1288490188800
25      session1657857376284    ad51539607573  link1288490188800
26       session755914244159    ad51539607599  link1288490188800
27      session1571958030356    ad51539607574  link1288490188800
28      session1589137899580    ad60129542179  link1288490188800
29       session292057776215    ad60129542176  link1288490188800
...                      ...              ...                ...
199380  session1082331758607  ad1400159338542  link1657857376281
199381   session223338299470  ad1425929142321  link1657857376281
199382  session1451698946090  ad1511828488250  link1657857376281
199383  session1434519076883  ad1657857376304  link1657857376281
199384   session111669149700  ad1700807049247  link1657857376281
199385  session1589137899603   ad128849018915  link1657857376258
199386  session1108101562426  ad1322849927226  link1657857376258
199387  session1649267441741  ad1683627180052  link1657857376258
199388  session1159641169963             noad  link1657857376276
199389  session1176821039157   ad523986010169  link1657857376276
199390  session1185410973742             noad  link1657857376271
199391  session1425929142350             noad  link1657857376267
199392  session1425929142350             noad  link1657857376267
199393  session1477468749836             noad  link1657857376260
199394             session75             noad  link1657857376259
199395    session94489280529             noad  link1657857376259
199396   session481036337183             noad  link1657857376259
199397  session1194000908300             noad  link1657857376259
199398   session197568495721    ad25769803803  link1657857376257
199399  session1331439861761   ad266287972383  link1657857376257
199400   session197568495721    ad25769803803  link1657857376257
199401  session1331439861761   ad266287972383  link1657857376257
199402    session94489280609   ad996432412677  link1657857376263
199403   session704374636553   ad919123001358  link1657857376264
199404   session420906795070  ad1563368095799  link1657857376266
199405   session695784701988             noad  link1657857376273
199406  session1245540515886             noad  link1657857376273
199407  session1348619730991             noad  link1657857376273
199408   session412316860455  ad1228360646711  link1657857376273
199409  session1675037245453  ad1348619730974  link1657857376273

                            timestamp  checkout  order_placed  \
0       2018-04-30T14:39:22.000-04:00         1             1
1       2018-04-30T08:39:23.000-04:00         1             1
2       2018-04-30T17:24:01.000-04:00         1             1
3       2018-04-30T10:42:57.000-04:00         1             1
4       2018-04-30T10:43:19.000-04:00         1             1
5       2018-04-30T22:58:04.000-04:00         1             1
6       2018-04-30T16:47:21.000-04:00         1             1
7       2018-04-30T15:57:36.000-04:00         1             1
8       2018-04-30T16:10:54.000-04:00         1             1
9       2018-04-30T08:19:05.000-04:00         1             1
10      2018-04-30T14:15:55.000-04:00         1             1
11      2018-04-30T16:02:51.000-04:00         1             0
12      2018-04-30T13:20:54.000-04:00         1             1
13      2018-04-30T13:02:41.000-04:00         1             1
14      2018-04-30T19:39:19.000-04:00         1             0
15      2018-04-30T14:57:38.000-04:00         1             1
16      2018-04-30T22:54:40.000-04:00         1             1
17      2018-04-30T21:34:55.000-04:00         1             1
18      2018-04-30T11:35:05.000-04:00         1             1
19      2018-04-30T14:56:47.000-04:00         1             1
20      2018-04-30T18:32:49.000-04:00         1             1
21      2018-04-30T14:15:04.000-04:00         0             1
22      2018-04-30T13:28:22.000-04:00         1             1
23      2018-04-30T19:53:57.000-04:00         1             1
24      2018-04-30T14:26:05.000-04:00         1             1
25      2018-04-30T11:00:32.000-04:00         1             1
26      2018-04-30T18:14:40.000-04:00         1             1
27      2018-04-30T14:34:44.000-04:00         1             0
28      2018-04-30T16:32:30.000-04:00         1             1
29      2018-04-30T22:30:22.000-04:00         1             1
...                               ...       ...           ...
199380  2018-04-30T10:21:57.000-04:00         1             0
199381  2018-04-30T21:53:46.000-04:00         0             0
199382  2018-04-30T15:36:26.000-04:00         0             0
199383  2018-04-30T10:31:33.000-04:00         1             1
199384  2018-04-30T06:24:16.000-04:00         0             0
199385  2018-04-30T21:19:48.000-04:00         1             0
199386  2018-04-30T18:57:24.000-04:00         0             0
199387  2018-04-30T22:06:27.000-04:00         1             0
199388  2018-04-30T14:04:44.000-04:00         0             0
199389  2018-04-30T15:11:58.000-04:00         0             0
199390  2018-04-30T16:26:17.000-04:00         0             0
199391  2018-04-30T20:46:09.000-04:00         1             0
199392  2018-04-30T20:46:09.000-04:00         1             0
199393  2018-04-30T09:46:33.000-04:00         0             0
199394  2018-04-30T20:56:29.000-04:00         1             0
199395  2018-04-30T11:08:54.000-04:00         1             1
199396  2018-04-30T12:06:56.000-04:00         0             0
199397  2018-04-30T10:41:50.000-04:00         0             0
199398  2018-04-30T22:03:12.000-04:00         0             0
199399  2018-04-30T00:53:51.000-04:00         0             0
199400  2018-04-30T22:03:12.000-04:00         0             0
199401  2018-04-30T00:53:51.000-04:00         0             0
199402  2018-04-30T21:12:27.000-04:00         0             0
199403  2018-04-30T12:50:24.000-04:00         0             0
199404  2018-04-30T16:57:56.000-04:00         0             0
199405  2018-04-30T13:40:18.000-04:00         0             1
199406  2018-04-30T15:20:54.000-04:00         0             0
199407  2018-04-30T17:15:26.000-04:00         1             0
199408  2018-04-30T14:33:32.000-04:00         0             0
199409  2018-04-30T09:24:21.000-04:00         0             0

                     grp funnel_level
0        grp936302870529        lower
1        grp936302870529        lower
2        grp936302870529        lower
3        grp936302870529        lower
4        grp936302870529        lower
5        grp111669149696        lower
6        grp111669149696        lower
7        grp111669149696        lower
8        grp111669149696        lower
9        grp111669149696        lower
10       grp111669149696        lower
11       grp111669149696        lower
12       grp111669149696        lower
13       grp111669149696        lower
14       grp111669149696        lower
15       grp111669149696        lower
16       grp111669149696        lower
17       grp111669149696        lower
18       grp111669149696        lower
19       grp111669149696        lower
20       grp111669149696        lower
21       grp111669149696        lower
22       grp111669149696        lower
23       grp111669149696        lower
24       grp111669149696        lower
25       grp111669149696        lower
26       grp111669149696        lower
27       grp111669149696        lower
28       grp111669149696        lower
29       grp111669149696        lower
...                  ...          ...
199380  grp1589137899520       middle
199381  grp1589137899520       middle
199382  grp1589137899520       middle
199383  grp1589137899520       middle
199384  grp1589137899520       middle
199385   grp369367187456        upper
199386   grp369367187456        upper
199387   grp369367187456        upper
199388  grp1340029796352        upper
199389  grp1340029796352        upper
199390  grp1073741824001        upper
199391   grp987842478080        upper
199392  grp1073741824000        upper
199393   grp446676598784        upper
199394   grp446676598784        upper
199395   grp446676598784        upper
199396   grp446676598784        upper
199397   grp446676598784        upper
199398   grp687194767360        upper
199399   grp687194767360        upper
199400   grp343597383680        upper
199401   grp343597383680        upper
199402   grp936302870528        upper
199403   grp936302870528        upper
199404   grp936302870528        upper
199405  grp1254130450432        upper
199406  grp1254130450432        upper
199407  grp1254130450432        upper
199408  grp1254130450432        upper
199409  grp1254130450432        upper

[199410 rows x 8 columns]

In [13]:
train_copy

,id,ad,link,timestamp,checkout,order_placed,grp,funnel_level
0,session446676598812,ad412316860435,link1288490188810,2018-04-30T14:39:22.000-04:00,1,1,grp936302870529,lower
1,session60129542152,ad584115552306,link1288490188810,2018-04-30T08:39:23.000-04:00,1,1,grp936302870529,lower
2,session1511828488251,ad1056561954841,link1288490188810,2018-04-30T17:24:01.000-04:00,1,1,grp936302870529,lower
3,session1142461300754,ad1666447310876,link1288490188810,2018-04-30T10:42:57.000-04:00,1,1,grp936302870529,lower
4,session1142461300754,ad1666447310876,link1288490188810,2018-04-30T10:43:19.000-04:00,1,1,grp936302870529,lower
5,session1314259992659,ad34,link1288490188800,2018-04-30T22:58:04.000-04:00,1,1,grp111669149696,lower
6,session206158430275,ad38,link1288490188800,2018-04-30T16:47:21.000-04:00,1,1,grp111669149696,lower
7,session8589934632,ad14,link1288490188800,2018-04-30T15:57:36.000-04:00,1,1,grp111669149696,lower
8,session523986010167,ad15,link1288490188800,2018-04-30T16:10:54.000-04:00,1,1,grp111669149696,lower
9,session1357209665542,ad58,link1288490188800,2018-04-30T08:19:05.000-04:00,1,1,grp111669149696,lower
10,session1236950581279,ad8589934618,link1288490188800,2018-04-30T14:15:55.000-04:00,1,1,grp111669149696,lower
11,session1546188226610,ad8589934595,link1288490188800,2018-04-30T16:02:51.000-04:00,1,0,grp111669149696,lower
12,session695784701963,ad8589934598,link1288490188800,2018-04-30T13:20:54.000-04:00,1,1,grp111669149696,lower
13,session309237645347,ad17179869208,link1288490188800,2018-04-30T13:02:41.000-04:00,1,1,grp111669149696,lower
14,session858993459270,ad17179869188,link1288490188800,2018-04-30T19:39:19.000-04:00,1,0,grp111669149696,lower
15,session584115552299,ad25769803828,link1288490188800,2018-04-30T14:57:38.000-04:00,1,1,grp111669149696,lower
16,session944892805202,ad25769803781,link1288490188800,2018-04-30T22:54:40.000-04:00,1,1,grp111669149696,lower
17,session695784702028,ad25769803791,link1288490188800,2018-04-30T21:34:55.000-04:00,1,1,grp111669149696,lower
18,session1108101562390,ad34359738435,link1288490188800,2018-04-30T11:35:05.000-04:00,1,1,grp111669149696,lower
19,session755914244140,ad34359738430,link1288490188800,2018-04-30T14:56:47.000-04:00,1,1,grp111669149696,lower
20,session1245540515897,ad34359738407,link1288490188800,2018-04-30T18:32:49.000-04:00,1,1,grp111669149696,lower
21,session25769803819,ad42949672981,link1288490188800,2018-04-30T14:15:04.000-04:00,0,1,grp111669149696,lower
22,session1219770712099,ad51539607565,link1288490188800,2018-04-30T13:28:22.000-04:00,1,1,grp111669149696,lower
23,session919123001364,ad51539607591,link1288490188800,2018-04-30T19:53:57.000-04:00,1,1,grp111669149696,lower
24,session1632087572522,ad51539607555,link1288490188800,2018-04-30T14:26:05.000-04:00,1,1,grp111669149696,lower
25,session1657857376284,ad51539607573,link1288490188800,2018-04-30T11:00:32.000-04:00,1,1,grp111669149696,lower
26,session755914244159,ad51539607599,link1288490188800,2018-04-30T18:14:40.000-04:00,1,1,grp111669149696,lower
27,session1571958030356,ad51539607574,link1288490188800,2018-04-30T14:34:44.000-04:00,1,0,grp111669149696,lower
28,session1589137899580,ad60129542179,link1288490188800,2018-04-30T16:32:30.000-04:00,1,1,grp111669149696,lower
29,session292057776215,ad60129542176,link1288490188800,2018-04-30T22:30:22.000-04:00,1,1,grp111669149696,lower
...,...,...,...,...,...,...,...,...
199380,session1082331758607,ad1400159338542,link1657857376281,2018-04-30T10:21:57.000-04:00,1,0,grp1589137899520,middle
199381,session223338299470,ad1425929142321,link1657857376281,2018-04-30T21:53:46.000-04:00,0,0,grp1589137899520,middle
199382,session1451698946090,ad1511828488250,link1657857376281,2018-04-30T15:36:26.000-04:00,0,0,grp1589137899520,middle
199383,session1434519076883,ad1657857376304,link1657857376281,2018-04-30T10:31:33.000-04:00,1,1,grp1589137899520,middle
199384,session111669149700,ad1700807049247,link1657857376281,2018-04-30T06:24:16.000-04:00,0,0,grp1589137899520,middle
199385,session1589137899603,ad128849018915,link1657857376258,2018-04-30T21:19:48.000-04:00,1,0,grp369367187456,upper
199386,session1108101562426,ad1322849927226,link1657857376258,2018-04-30T18:57:24.000-04:00,0,0,grp369367187456,upper
199387,session1649267441741,ad1683627180052,link1657857376258,2018-04-30T22:06:27.000-04:00,1,0,grp369367187456,upper
199388,session1159641169963,noad,link1657857376276,2018-04-30T14:04:44.000-04:00,0,0,grp1340029796352,upper
199389,session1176821039157,ad523986010169,link1657857376276,2018-04-30T15:11:58.000-04:00,0,0,grp1340029796352,upper
199390,session1185410973742,noad,link1657857376271,2018-04-30T16:26:17.000-04:00,0,0,grp1073741824001,upper
199391,session1425929142350,noad,link1657857376267,2018-04-30T20:46:09.000-04:00,1,0,grp987842478080,upper
199392,session1425929142350,noad,link1657857376267,2018-04-30T20:46:09.000-04:00,1,0,grp1073741824000,upper
199393,session1477468749836,noad,link1657857376260,2018-04-30T09:46:33.000-04:00,0,0,grp446676598784,upper
199394,session75,noad,link1657857376259,2018-04-30T20:56:29.000-04:00,1,0,grp446676598784,upper
199395,session94489280529,noad,link1657857376259,2018-04-30T11:08:54.000-04:00,1,1,grp446676598784,upper
199396,session481036337183,noad,link1657857376259,2018-04-30T12:06:56.000-04:00,0,0,grp446676598784,upper
199397,session1194000908300,noad,link1657857376259,2018-04-30T10:41:50.000-04:00,0,0,grp446676598784,upper
199398,session197568495721,ad25769803803,link1657857376257,2018-04-30T22:03:12.000-04:00,0,0,grp687194767360,upper
199399,session1331439861761,ad266287972383,link1657857376257,2018-04-30T00:53:51.000-04:00,0,0,grp687194767360,upper
199400,session197568495721,ad25769803803,link1657857376257,2018-04-30T22:03:12.000-04:00,0,0,grp343597383680,upper
199401,session1331439861761,ad266287972383,link1657857376257,2018-04-30T00:53:51.000-04:00,0,0,grp343597383680,upper
199402,session94489280609,ad996432412677,link1657857376263,2018-04-30T21:12:27.000-04:00,0,0,grp936302870528,upper
199403,session704374636553,ad919123001358,link1657857376264,2018-04-30T12:50:24.000-04:00,0,0,grp936302870528,upper
199404,session420906795070,ad1563368095799,link1657857376266,2018-04-30T16:57:56.000-04:00,0,0,grp936302870528,upper
199405,session695784701988,noad,link1657857376273,2018-04-30T13:40:18.000-04:00,0,1,grp1254130450432,upper
199406,session1245540515886,noad,link1657857376273,2018-04-30T15:20:54.000-04:00,0,0,grp1254130450432,upper
199407,session1348619730991,noad,link1657857376273,2018-04-30T17:15:26.000-04:00,1,0,grp1254130450432,upper
199408,session412316860455,ad1228360646711,link1657857376273,2018-04-30T14:33:32.000-04:00,0,0,grp1254130450432,upper
199409,session1675037245453,ad1348619730974,link1657857376273,2018-04-30T09:24:21.000-04:00,0,0,grp1254130450432,upper

In [14]:
for i in list(train.columns):
    encoding_label(i)

id
['session************' 'session0' 'session10' ... 'session996432412740'
 'session996432412741' 'session996432412743']
0          9026
1         10374
2          4564
3          1278
4          1278
5          2864
6          6798
7         12772
8          9719
9          3151
10         2161
11         4826
12        11212
13         7726
14        12662
15        10205
16        13479
17        11268
18          947
19        11732
20         2231
21         7269
22         2017
23        13212
24         5614
25         5873
26        11745
27         5072
28         5251
29         7615
          ...
199380      740
199381     6958
199382     3978
199383     3844
199384     1019
199385     5270
199386      975
199387     5849
199388     1454
199389     1603
199390     1679
199391     3824
199392     3824
199393     4242
199394    11698
199395    13496
199396     9308
199397     1728
199398     6736
199399     2943
199400     6736
199401     2943
199402    13560
199403    11289
199404     8762
199405    11235
199406     2222
199407     3122
199408     8680
199409     6005
Name: id, Length: 199410, dtype: int64
ad
['ad************' 'ad0' 'ad1' ... 'ad996432412728' 'ad996432412729' 'noad']
0          6332
1          7463
2           404
3          4364
4          4364
5          5798
6          6148
7          2619
8          3278
9          7429
10         9395
11         9347
12         9375
13         4731
14         4696
15         5328
16         5279
17         5300
18         5910
19         5907
20         5889
21         6483
22         7061
23         7083
24         7031
25         7068
26         7090
27         7069
28         7624
29         7622
          ...
199380     2660
199381     2822
199382     3379
199383     4328
199384     4578
199385     1933
199386     2161
199387     4470
199388    10362
199389     7144
199390    10362
199391    10362
199392    10362
199393    10362
199394    10362
199395    10362
199396    10362
199397    10362
199398     5307
199399     5360
199400     5307
199401     5360
199402    10318
199403     9772
199404     3749
199405    10362
199406    10362
199407    10362
199408     1537
199409     2287
Name: ad, Length: 199410, dtype: int64
link
['link************' 'link0' 'link1' ... 'link996432412702'
 'link996432412703' 'link996432412704']
0          952
1          952
2          952
3          952
4          952
5          943
6          943
7          943
8          943
9          943
10         943
11         943
12         943
13         943
14         943
15         943
16         943
17         943
18         943
19         943
20         943
21         943
22         943
23         943
24         943
25         943
26         943
27         943
28         943
29         943
          ...
199380    2223
199381    2223
199382    2223
199383    2223
199384    2223
199385    2204
199386    2204
199387    2204
199388    2218
199389    2218
199390    2215
199391    2212
199392    2212
199393    2206
199394    2205
199395    2205
199396    2205
199397    2205
199398    2203
199399    2203
199400    2203
199401    2203
199402    2209
199403    2210
199404    2211
199405    2216
199406    2216
199407    2216
199408    2216
199409    2216
Name: link, Length: 199410, dtype: int64
timestamp is skipped
checkout is not need
order_placed is not need
grp
['grp0' 'grp1013612281856' 'grp1022202216448' 'grp1022202216449'
 'grp1039382085632' 'grp1047972020224' 'grp1056561954816'
 'grp1073741824000' 'grp1073741824001' 'grp1090921693184'
 'grp1108101562368' 'grp111669149696' 'grp1159641169920'
 'grp1194000908288' 'grp1245540515840' 'grp1254130450432'
 'grp1254130450433' 'grp1254130450434' 'grp1271310319616'
 'grp1279900254208' 'grp1279900254209' 'grp1279900254210'
 'grp1279900254211' 'grp128849018880' 'grp1297080123392'
 'grp1314259992576' 'grp1314259992577' 'grp1322849927168'
 'grp1340029796352' 'grp1357209665536' 'grp1357209665537'
 'grp1357209665538' 'grp1391569403904' 'grp1425929142272'
 'grp1434519076864' 'grp1434519076865' 'grp1443109011456'
 'grp1468878815232' 'grp1468878815233' 'grp1494648619008'
 'grp1511828488192' 'grp1511828488193' 'grp1520418422784'
 'grp1529008357376' 'grp1571958030336' 'grp1580547964928'
 'grp1589137899520' 'grp1606317768704' 'grp163208757248'
 'grp1649267441664' 'grp1666447310848' 'grp1709396983808'
 'grp1709396983809' 'grp17179869184' 'grp17179869185' 'grp180388626432'
 'grp197568495616' 'grp206158430208' 'grp214748364800' 'grp249108103168'
 'grp257698037760' 'grp257698037761' 'grp283467841536' 'grp309237645312'
 'grp309237645313' 'grp317827579904' 'grp317827579905' 'grp317827579906'
 'grp326417514496' 'grp34359738368' 'grp343597383680' 'grp343597383681'
 'grp369367187456' 'grp377957122048' 'grp429496729600' 'grp438086664192'
 'grp446676598784' 'grp463856467968' 'grp489626271744' 'grp489626271745'
 'grp489626271746' 'grp498216206336' 'grp51539607552' 'grp523986010112'
 'grp566935683072' 'grp584115552256' 'grp601295421440' 'grp627065225216'
 'grp635655159808' 'grp644245094400' 'grp670014898176' 'grp687194767360'
 'grp704374636544' 'grp721554505728' 'grp738734374912' 'grp764504178688'
 'grp841813590016' 'grp85899345920' 'grp919123001344' 'grp927712935936'
 'grp936302870528' 'grp936302870529' 'grp94489280512' 'grp962072674304'
 'grp970662608896' 'grp979252543488' 'grp987842478080' 'grp996432412672']
0         101
1         101
2         101
3         101
4         101
5          11
6          11
7          11
8          11
9          11
10         11
11         11
12         11
13         11
14         11
15         11
16         11
17         11
18         11
19         11
20         11
21         11
22         11
23         11
24         11
25         11
26         11
27         11
28         11
29         11
         ...
199380     46
199381     46
199382     46
199383     46
199384     46
199385     72
199386     72
199387     72
199388     28
199389     28
199390      8
199391    106
199392      7
199393     76
199394     76
199395     76
199396     76
199397     76
199398     91
199399     91
199400     70
199401     70
199402    100
199403    100
199404    100
199405     15
199406     15
199407     15
199408     15
199409     15
Name: grp, Length: 199410, dtype: int64
funnel_level
['lower' 'middle' 'upper']
0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        0
24        0
25        0
26        0
27        0
28        0
29        0
         ..
199380    1
199381    1
199382    1
199383    1
199384    1
199385    2
199386    2
199387    2
199388    2
199389    2
199390    2
199391    2
199392    2
199393    2
199394    2
199395    2
199396    2
199397    2
199398    2
199399    2
199400    2
199401    2
199402    2
199403    2
199404    2
199405    2
199406    2
199407    2
199408    2
199409    2
Name: funnel_level, Length: 199410, dtype: int64

In [15]:
len(train_copy['timestamp'])

199410

In [16]:
train_copy

,id,ad,link,timestamp,checkout,order_placed,grp,funnel_level
0,9026,6332,952,2018-04-30T14:39:22.000-04:00,1,1,101,0
1,10374,7463,952,2018-04-30T08:39:23.000-04:00,1,1,101,0
2,4564,404,952,2018-04-30T17:24:01.000-04:00,1,1,101,0
3,1278,4364,952,2018-04-30T10:42:57.000-04:00,1,1,101,0
4,1278,4364,952,2018-04-30T10:43:19.000-04:00,1,1,101,0
5,2864,5798,943,2018-04-30T22:58:04.000-04:00,1,1,11,0
6,6798,6148,943,2018-04-30T16:47:21.000-04:00,1,1,11,0
7,12772,2619,943,2018-04-30T15:57:36.000-04:00,1,1,11,0
8,9719,3278,943,2018-04-30T16:10:54.000-04:00,1,1,11,0
9,3151,7429,943,2018-04-30T08:19:05.000-04:00,1,1,11,0
10,2161,9395,943,2018-04-30T14:15:55.000-04:00,1,1,11,0
11,4826,9347,943,2018-04-30T16:02:51.000-04:00,1,0,11,0
12,11212,9375,943,2018-04-30T13:20:54.000-04:00,1,1,11,0
13,7726,4731,943,2018-04-30T13:02:41.000-04:00,1,1,11,0
14,12662,4696,943,2018-04-30T19:39:19.000-04:00,1,0,11,0
15,10205,5328,943,2018-04-30T14:57:38.000-04:00,1,1,11,0
16,13479,5279,943,2018-04-30T22:54:40.000-04:00,1,1,11,0
17,11268,5300,943,2018-04-30T21:34:55.000-04:00,1,1,11,0
18,947,5910,943,2018-04-30T11:35:05.000-04:00,1,1,11,0
19,11732,5907,943,2018-04-30T14:56:47.000-04:00,1,1,11,0
20,2231,5889,943,2018-04-30T18:32:49.000-04:00,1,1,11,0
21,7269,6483,943,2018-04-30T14:15:04.000-04:00,0,1,11,0
22,2017,7061,943,2018-04-30T13:28:22.000-04:00,1,1,11,0
23,13212,7083,943,2018-04-30T19:53:57.000-04:00,1,1,11,0
24,5614,7031,943,2018-04-30T14:26:05.000-04:00,1,1,11,0
25,5873,7068,943,2018-04-30T11:00:32.000-04:00,1,1,11,0
26,11745,7090,943,2018-04-30T18:14:40.000-04:00,1,1,11,0
27,5072,7069,943,2018-04-30T14:34:44.000-04:00,1,0,11,0
28,5251,7624,943,2018-04-30T16:32:30.000-04:00,1,1,11,0
29,7615,7622,943,2018-04-30T22:30:22.000-04:00,1,1,11,0
...,...,...,...,...,...,...,...,...
199380,740,2660,2223,2018-04-30T10:21:57.000-04:00,1,0,46,1
199381,6958,2822,2223,2018-04-30T21:53:46.000-04:00,0,0,46,1
199382,3978,3379,2223,2018-04-30T15:36:26.000-04:00,0,0,46,1
199383,3844,4328,2223,2018-04-30T10:31:33.000-04:00,1,1,46,1
199384,1019,4578,2223,2018-04-30T06:24:16.000-04:00,0,0,46,1
199385,5270,1933,2204,2018-04-30T21:19:48.000-04:00,1,0,72,2
199386,975,2161,2204,2018-04-30T18:57:24.000-04:00,0,0,72,2
199387,5849,4470,2204,2018-04-30T22:06:27.000-04:00,1,0,72,2
199388,1454,10362,2218,2018-04-30T14:04:44.000-04:00,0,0,28,2
199389,1603,7144,2218,2018-04-30T15:11:58.000-04:00,0,0,28,2
199390,1679,10362,2215,2018-04-30T16:26:17.000-04:00,0,0,8,2
199391,3824,10362,2212,2018-04-30T20:46:09.000-04:00,1,0,106,2
199392,3824,10362,2212,2018-04-30T20:46:09.000-04:00,1,0,7,2
199393,4242,10362,2206,2018-04-30T09:46:33.000-04:00,0,0,76,2
199394,11698,10362,2205,2018-04-30T20:56:29.000-04:00,1,0,76,2
199395,13496,10362,2205,2018-04-30T11:08:54.000-04:00,1,1,76,2
199396,9308,10362,2205,2018-04-30T12:06:56.000-04:00,0,0,76,2
199397,1728,10362,2205,2018-04-30T10:41:50.000-04:00,0,0,76,2
199398,6736,5307,2203,2018-04-30T22:03:12.000-04:00,0,0,91,2
199399,2943,5360,2203,2018-04-30T00:53:51.000-04:00,0,0,91,2
199400,6736,5307,2203,2018-04-30T22:03:12.000-04:00,0,0,70,2
199401,2943,5360,2203,2018-04-30T00:53:51.000-04:00,0,0,70,2
199402,13560,10318,2209,2018-04-30T21:12:27.000-04:00,0,0,100,2
199403,11289,9772,2210,2018-04-30T12:50:24.000-04:00,0,0,100,2
199404,8762,3749,2211,2018-04-30T16:57:56.000-04:00,0,0,100,2
199405,11235,10362,2216,2018-04-30T13:40:18.000-04:00,0,1,15,2
199406,2222,10362,2216,2018-04-30T15:20:54.000-04:00,0,0,15,2
199407,3122,10362,2216,2018-04-30T17:15:26.000-04:00,1,0,15,2
199408,8680,1537,2216,2018-04-30T14:33:32.000-04:00,0,0,15,2
199409,6005,2287,2216,2018-04-30T09:24:21.000-04:00,0,0,15,2

In [17]:
a=[]
for i in train_copy['timestamp']:
#     i=str(i)
    i=i.replace(i[0:11],'')
    i=i.replace('.000-04:00','')
    a.append(i)

In [18]:
train_copy['timestamp']=a

In [19]:
train_copy

,id,ad,link,timestamp,checkout,order_placed,grp,funnel_level
0,9026,6332,952,14:39:22,1,1,101,0
1,10374,7463,952,08:39:23,1,1,101,0
2,4564,404,952,17:24:01,1,1,101,0
3,1278,4364,952,10:42:57,1,1,101,0
4,1278,4364,952,10:43:19,1,1,101,0
5,2864,5798,943,22:58:04,1,1,11,0
6,6798,6148,943,16:47:21,1,1,11,0
7,12772,2619,943,15:57:36,1,1,11,0
8,9719,3278,943,16:10:54,1,1,11,0
9,3151,7429,943,08:19:05,1,1,11,0
10,2161,9395,943,14:15:55,1,1,11,0
11,4826,9347,943,16:02:51,1,0,11,0
12,11212,9375,943,13:20:54,1,1,11,0
13,7726,4731,943,13:02:41,1,1,11,0
14,12662,4696,943,19:39:19,1,0,11,0
15,10205,5328,943,14:57:38,1,1,11,0
16,13479,5279,943,22:54:40,1,1,11,0
17,11268,5300,943,21:34:55,1,1,11,0
18,947,5910,943,11:35:05,1,1,11,0
19,11732,5907,943,14:56:47,1,1,11,0
20,2231,5889,943,18:32:49,1,1,11,0
21,7269,6483,943,14:15:04,0,1,11,0
22,2017,7061,943,13:28:22,1,1,11,0
23,13212,7083,943,19:53:57,1,1,11,0
24,5614,7031,943,14:26:05,1,1,11,0
25,5873,7068,943,11:00:32,1,1,11,0
26,11745,7090,943,18:14:40,1,1,11,0
27,5072,7069,943,14:34:44,1,0,11,0
28,5251,7624,943,16:32:30,1,1,11,0
29,7615,7622,943,22:30:22,1,1,11,0
...,...,...,...,...,...,...,...,...
199380,740,2660,2223,10:21:57,1,0,46,1
199381,6958,2822,2223,21:53:46,0,0,46,1
199382,3978,3379,2223,15:36:26,0,0,46,1
199383,3844,4328,2223,10:31:33,1,1,46,1
199384,1019,4578,2223,06:24:16,0,0,46,1
199385,5270,1933,2204,21:19:48,1,0,72,2
199386,975,2161,2204,18:57:24,0,0,72,2
199387,5849,4470,2204,22:06:27,1,0,72,2
199388,1454,10362,2218,14:04:44,0,0,28,2
199389,1603,7144,2218,15:11:58,0,0,28,2
199390,1679,10362,2215,16:26:17,0,0,8,2
199391,3824,10362,2212,20:46:09,1,0,106,2
199392,3824,10362,2212,20:46:09,1,0,7,2
199393,4242,10362,2206,09:46:33,0,0,76,2
199394,11698,10362,2205,20:56:29,1,0,76,2
199395,13496,10362,2205,11:08:54,1,1,76,2
199396,9308,10362,2205,12:06:56,0,0,76,2
199397,1728,10362,2205,10:41:50,0,0,76,2
199398,6736,5307,2203,22:03:12,0,0,91,2
199399,2943,5360,2203,00:53:51,0,0,91,2
199400,6736,5307,2203,22:03:12,0,0,70,2
199401,2943,5360,2203,00:53:51,0,0,70,2
199402,13560,10318,2209,21:12:27,0,0,100,2
199403,11289,9772,2210,12:50:24,0,0,100,2
199404,8762,3749,2211,16:57:56,0,0,100,2
199405,11235,10362,2216,13:40:18,0,1,15,2
199406,2222,10362,2216,15:20:54,0,0,15,2
199407,3122,10362,2216,17:15:26,1,0,15,2
199408,8680,1537,2216,14:33:32,0,0,15,2
199409,6005,2287,2216,09:24:21,0,0,15,2

In [20]:
l=[]
def get_sec(time_str):
    for i in time_str:
        h, m, s = i.split(':')
        l.append(int(h) * 3600 + int(m) * 60 + int(s))
    return l

In [21]:
a=get_sec(train_copy['timestamp'])

In [22]:
a

[52762,
 31163,
 62641,
 38577,
 38599,
 82684,
 60441,
 57456,
 58254,
 29945,
 51355,
 57771,
 48054,
 46961,
 70759,
 53858,
 82480,
 77695,
 41705,
 53807,
 66769,
 51304,
 48502,
 71637,
 51965,
 39632,
 65680,
 52484,
 59550,
 81022,
 83920,
 69393,
 56991,
 41594,
 41241,
 40555,
 49925,
 50540,
 45680,
 79134,
 56377,
 85530,
 55129,
 35534,
 59241,
 74606,
 50596,
 56070,
 55755,
 72737,
 78872,
 66666,
 27186,
 38033,
 40463,
 55118,
 74556,
 50279,
 73460,
 48644,
 71573,
 65687,
 80631,
 37384,
 69743,
 48512,
 72776,
 75798,
 45359,
 51308,
 82251,
 82487,
 71541,
 57594,
 45230,
 74972,
 46100,
 84839,
 59834,
 35477,
 35059,
 54618,
 41808,
 70910,
 52916,
 53169,
 53796,
 80251,
 78816,
 59822,
 76094,
 34694,
 45821,
 59167,
 39890,
 57312,
 57666,
 44113,
 41037,
 57409,
 69628,
 8614,
 48686,
 43829,
 53433,
 61503,
 66456,
 48909,
 56526,
 68861,
 79237,
 77460,
 58309,
 46203,
 48608,
 42590,
 76626,
 40676,
 53087,
 76285,
 75110,
 33715,
 52719,
 39477,
 40758,
 68119,
 51361,
 76222,
 74971,
 68220,
 52411,
 47070,
 50046,
 30460,
 65252,
 35821,
 78485,
 40874,
 33934,
 47363,
 78113,
 35922,
 79888,
 34819,
 41458,
 51822,
 32482,
 49325,
 55957,
 43885,
 78112,
 86154,
 57741,
 58154,
 58544,
 39034,
 21200,
 77660,
 38532,
 44389,
 56448,
 36987,
 46577,
 57140,
 72002,
 12277,
 1248,
 59240,
 40997,
 85930,
 59054,
 46972,
 80817,
 12686,
 47878,
 75893,
 52220,
 48055,
 68324,
 48221,
 42077,
 67458,
 34078,
 41227,
 69982,
 73910,
 76650,
 44968,
 77472,
 68225,
 53294,
 80099,
 75309,
 74675,
 51570,
 61815,
 68726,
 56117,
 49290,
 33983,
 43081,
 76265,
 86098,
 81816,
 42942,
 60841,
 40165,
 35406,
 48379,
 39735,
 77561,
 78146,
 37489,
 69536,
 27743,
 40636,
 44780,
 79125,
 82164,
 58780,
 85127,
 36129,
 58080,
 60849,
 81718,
 38731,
 36936,
 25960,
 48429,
 31178,
 62676,
 38725,
 66254,
 77015,
 31266,
 67430,
 49707,
 74340,
 26864,
 69548,
 32805,
 62145,
 65322,
 72470,
 39367,
 42066,
 55970,
 31003,
 60410,
 58135,
 54736,
 37108,
 52422,
 54181,
 46204,
 27915,
 80535,
 85226,
 57958,
 75638,
 73853,
 37299,
 77474,
 77961,
 82191,
 46149,
 38701,
 71972,
 59263,
 70349,
 35100,
 45034,
 50125,
 78495,
 43793,
 74077,
 48088,
 54450,
 71619,
 65887,
 31027,
 60702,
 72465,
 57709,
 9866,
 12404,
 83079,
 68373,
 46589,
 63677,
 83086,
 56600,
 41849,
 44764,
 62655,
 60648,
 4071,
 63554,
 46812,
 51383,
 79247,
 40186,
 44118,
 49299,
 32368,
 44131,
 42749,
 62728,
 50837,
 68234,
 62916,
 62106,
 41800,
 66430,
 60421,
 61281,
 34141,
 38640,
 70225,
 37645,
 40051,
 76812,
 55281,
 46878,
 63765,
 55572,
 68336,
 70459,
 58443,
 61690,
 53350,
 77731,
 76864,
 69151,
 1780,
 75586,
 28184,
 61059,
 49048,
 66083,
 186,
 58607,
 83456,
 58379,
 50977,
 45627,
 65157,
 54705,
 58386,
 79883,
 77690,
 69781,
 77515,
 68028,
 61222,
 78047,
 31869,
 51902,
 42429,
 52082,
 44429,
 52378,
 73739,
 67175,
 51446,
 66695,
 82315,
 82840,
 70604,
 56713,
 38317,
 56342,
 28772,
 51012,
 45572,
 37927,
 74056,
 67519,
 59529,
 59118,
 85313,
 68853,
 43820,
 70087,
 24571,
 77670,
 56779,
 37864,
 62716,
 54861,
 74837,
 60350,
 82979,
 43594,
 49468,
 39718,
 84594,
 54018,
 35814,
 36844,
 39580,
 82981,
 66197,
 68327,
 67766,
 39512,
 30793,
 45272,
 43742,
 57613,
 38965,
 27078,
 69829,
 2572,
 60291,
 84306,
 52148,
 64778,
 50953,
 40187,
 50858,
 51956,
 68589,
 57667,
 67779,
 73490,
 60647,
 48588,
 73959,
 55844,
 73819,
 41772,
 49164,
 51405,
 43600,
 42659,
 40025,
 43204,
 40906,
 36100,
 55515,
 44478,
 82388,
 33699,
 43884,
 50413,
 72913,
 39395,
 29707,
 63162,
 41483,
 51990,
 48785,
 37395,
 58128,
 82219,
 68066,
 72102,
 83049,
 39626,
 802,
 81145,
 39548,
 1217,
 35630,
 45206,
 52163,
 66407,
 8205,
 58089,
 64950,
 54689,
 57159,
 75918,
 42472,
 47076,
 47428,
 56450,
 56654,
 57405,
 55182,
 80039,
 50235,
 34782,
 5846,
 54670,
 64483,
 59949,
 37215,
 4980,
 34094,
 63599,
 48150,
 34807,
 79815,
 34563,
 44867,
 76200,
 66259,
 50004,
 73737,
 86079,
 28296,
 73891,
 52061,
 47477,
 79171,
 80911,
 49887,
 77580,
 34662,
 82005,
 42905,
 51692,
 46564,
 36187,
 44977,
 36040,
 46224,
 43519,
 78864,
 40076,
 76875,
 83576,
 52365,
 69040,
 60121,
 69122,
 77182,
 35522,
 44107,
 80278,
 73155,
 78485,
 34251,
 53306,
 2782,
 51998,
 49010,
 55573,
 53906,
 73083,
 53315,
 37414,
 40544,
 35732,
 64719,
 58213,
 46928,
 53934,
 38845,
 39806,
 40603,
 66052,
 36522,
 66621,
 44887,
 49109,
 50450,
 50040,
 54273,
 32476,
 71836,
 64232,
 63068,
 27167,
 47625,
 61798,
 41256,
 61669,
 65363,
 60401,
 52965,
 50366,
 84367,
 57976,
 83675,
 61413,
 85237,
 83038,
 78586,
 3065,
 61396,
 77738,
 50918,
 45740,
 59073,
 47310,
 41538,
 37238,
 79714,
 32202,
 5075,
 79355,
 63814,
 37517,
 31566,
 76041,
 56297,
 39321,
 36800,
 65618,
 68228,
 42778,
 32757,
 55483,
 37178,
 38444,
 33227,
 40367,
 41914,
 51329,
 59841,
 83080,
 62910,
 38412,
 61011,
 44671,
 38995,
 66768,
 43375,
 48786,
 55607,
 40345,
 57169,
 5729,
 41631,
 52273,
 61686,
 50138,
 79765,
 57041,
 43374,
 76176,
 68655,
 34158,
 41330,
 65626,
 42970,
 59876,
 36017,
 37983,
 72191,
 76738,
 59127,
 45746,
 47719,
 55163,
 65348,
 65357,
 45602,
 82979,
 86230,
 61564,
 71283,
 66246,
 48587,
 47751,
 45970,
 34281,
 45709,
 55352,
 62586,
 49959,
 34778,
 41826,
 57328,
 82928,
 83618,
 75218,
 76162,
 44482,
 46521,
 37198,
 81087,
 80832,
 54132,
 42647,
 42796,
 43163,
 39347,
 84546,
 30710,
 30922,
 30993,
 31065,
 41361,
 57741,
 66985,
 47460,
 53583,
 39709,
 53345,
 65887,
 17842,
 17928,
 49436,
 45432,
 45524,
 45588,
 45619,
 45625,
 47732,
 47753,
 47822,
 48682,
 48708,
 48866,
 48935,
 48942,
 49244,
 49259,
 49266,
 49297,
 48771,
 66855,
 59335,
 59348,
 59387,
 29756,
 29772,
 29778,
 72577,
 72585,
 72594,
 64829,
 64891,
 62689,
 55119,
 83973,
 23078,
 53367,
 53413,
 21404,
 21494,
 76852,
 45367,
 39529,
 47281,
 39492,
 39716,
 58410,
 44208,
 57715,
 84040,
 84043,
 45416,
 7074,
 34289,
 68866,
 69840,
 63454,
 63456,
 65229,
 65392,
 65440,
 69943,
 66306,
 60152,
 60033,
 60040,
 57831,
 47795,
 47802,
 47808,
 47822,
 47827,
 78855,
 76010,
 76643,
 37689,
 37908,
 48796,
 72770,
 18464,
 77464,
 77471,
 18138,
 18143,
 18151,
 18158,
 18186,
 41212,
 41214,
 41219,
 41300,
 41349,
 44698,
 78944,
 51330,
 73753,
 48952,
 51560,
 41448,
 42466,
 42498,
 62490,
 45772,
 43140,
 73782,
 73976,
 73809,
 2987,
 26514,
 41002,
 55174,
 48974,
 35405,
 77166,
 50768,
 84758,
 74116,
 58007,
 62395,
 59183,
 59571,
 59900,
 54918,
 58490,
 75178,
 39980,
 62323,
 7406,
 56142,
 56170,
 64859,
 65461,
 37530,
 56250,
 35947,
 72826,
 57598,
 53788,
 69329,
 52008,
 52318,
 34661,
 61517,
 69181,
 52949,
 84167,
 45435,
 52668,
 51868,
 39451,
 49990,
 76529,
 62926,
 52772,
 43442,
 41193,
 43751,
 25750,
 43335,
 62645,
 45038,
 60027,
 41386,
 50090,
 47351,
 75258,
 73480,
 34621,
 41493,
 59542,
 41763,
 39074,
 84249,
 52927,
 52785,
 57286,
 59488,
 85490,
 31448,
 61014,
 61161,
 38666,
 75667,
 71198,
 49326,
 65958,
 71688,
 62264,
 64002,
 75414,
 67927,
 67967,
 51338,
 70857,
 60293,
 62642,
 58591,
 69445,
 49646,
 26856,
 42390,
 42413,
 61838,
 61857,
 42173,
 78943,
 45859,
 40344,
 30311,
 78083,
 76552,
 74745,
 60477,
 60485,
 70735,
 64702,
 70180,
 44266,
 39785,
 45134,
 57290,
 58524,
 32046,
 59382,
 70098,
 36871,
 84528,
 52976,
 31443,
 59087,
 72003,
 44529,
 25978,
 25981,
 29933,
 72660,
 67796,
 35550,
 55238,
 79100,
 72909,
 41240,
 69794,
 70637,
 42687,
 42883,
 43141,
 64430,
 78427,
 26329,
 60779,
 28220,
 40181,
 64258,
 78753,
 41965,
 48458,
 78737,
 57511,
 48558,
 50747,
 40739,
 598,
 37807,
 49076,
 47180,
 49966,
 40592,
 69648,
 57940,
 61856,
 43328,
 43500,
 39992,
 79489,
 71199,
 77197,
 61928,
 41717,
 41740,
 61699,
 83865,
 36166,
 51730,
 80892,
 59313,
 34928,
 56945,
 41148,
 49543,
 47120,
 52099,
 39401,
 71781,
 39021,
 73260,
 18060,
 62624,
 49316,
 50141,
 62133,
 37930,
 33907,
 58852,
 61331,
 ...]

In [23]:
train_copy['timestamp']=a

In [24]:
train_copy

,id,ad,link,timestamp,checkout,order_placed,grp,funnel_level
0,9026,6332,952,52762,1,1,101,0
1,10374,7463,952,31163,1,1,101,0
2,4564,404,952,62641,1,1,101,0
3,1278,4364,952,38577,1,1,101,0
4,1278,4364,952,38599,1,1,101,0
5,2864,5798,943,82684,1,1,11,0
6,6798,6148,943,60441,1,1,11,0
7,12772,2619,943,57456,1,1,11,0
8,9719,3278,943,58254,1,1,11,0
9,3151,7429,943,29945,1,1,11,0
10,2161,9395,943,51355,1,1,11,0
11,4826,9347,943,57771,1,0,11,0
12,11212,9375,943,48054,1,1,11,0
13,7726,4731,943,46961,1,1,11,0
14,12662,4696,943,70759,1,0,11,0
15,10205,5328,943,53858,1,1,11,0
16,13479,5279,943,82480,1,1,11,0
17,11268,5300,943,77695,1,1,11,0
18,947,5910,943,41705,1,1,11,0
19,11732,5907,943,53807,1,1,11,0
20,2231,5889,943,66769,1,1,11,0
21,7269,6483,943,51304,0,1,11,0
22,2017,7061,943,48502,1,1,11,0
23,13212,7083,943,71637,1,1,11,0
24,5614,7031,943,51965,1,1,11,0
25,5873,7068,943,39632,1,1,11,0
26,11745,7090,943,65680,1,1,11,0
27,5072,7069,943,52484,1,0,11,0
28,5251,7624,943,59550,1,1,11,0
29,7615,7622,943,81022,1,1,11,0
...,...,...,...,...,...,...,...,...
199380,740,2660,2223,37317,1,0,46,1
199381,6958,2822,2223,78826,0,0,46,1
199382,3978,3379,2223,56186,0,0,46,1
199383,3844,4328,2223,37893,1,1,46,1
199384,1019,4578,2223,23056,0,0,46,1
199385,5270,1933,2204,76788,1,0,72,2
199386,975,2161,2204,68244,0,0,72,2
199387,5849,4470,2204,79587,1,0,72,2
199388,1454,10362,2218,50684,0,0,28,2
199389,1603,7144,2218,54718,0,0,28,2
199390,1679,10362,2215,59177,0,0,8,2
199391,3824,10362,2212,74769,1,0,106,2
199392,3824,10362,2212,74769,1,0,7,2
199393,4242,10362,2206,35193,0,0,76,2
199394,11698,10362,2205,75389,1,0,76,2
199395,13496,10362,2205,40134,1,1,76,2
199396,9308,10362,2205,43616,0,0,76,2
199397,1728,10362,2205,38510,0,0,76,2
199398,6736,5307,2203,79392,0,0,91,2
199399,2943,5360,2203,3231,0,0,91,2
199400,6736,5307,2203,79392,0,0,70,2
199401,2943,5360,2203,3231,0,0,70,2
199402,13560,10318,2209,76347,0,0,100,2
199403,11289,9772,2210,46224,0,0,100,2
199404,8762,3749,2211,61076,0,0,100,2
199405,11235,10362,2216,49218,0,1,15,2
199406,2222,10362,2216,55254,0,0,15,2
199407,3122,10362,2216,62126,1,0,15,2
199408,8680,1537,2216,52412,0,0,15,2
199409,6005,2287,2216,33861,0,0,15,2

In [25]:
train_copy.to_csv('train.csv',index=False)

In [135]:
X = [x for x in train_copy.columns if x not in ['order_placed','checkout']]
y=train_copy['order_placed']

In [136]:
X_train, X_test, y_train, y_test = train_test_split(train_copy[X], y, test_size=0.20, random_state=42)

In [137]:
xy=[X_train, X_test, y_train, y_test]
for i in xy:
    print(len(i))

159528
39882
159528
39882

for i in range(1,15):
    clf = RandomForestClassifier(n_estimators=100, max_depth=i,random_state=0)
    clf.fit(X_train,y_train)
    pre=clf.predict(X_test)
    print(i,accuracy_score(y_test, pre))

In [165]:
clf = MultinomialNB(alpha=0.001,fit_prior=False)
clf.fit(X_train,y_train)

MultinomialNB(alpha=0.001, class_prior=None, fit_prior=False)

In [166]:
pre=clf.predict(X_test)

In [167]:
print(accuracy_score(y_test, pre))

0.599669023619678

In [168]:
print(classification_report(pre,y_test))

             precision    recall  f1-score   support

          0       0.61      0.85      0.71     23155
          1       0.55      0.26      0.35     16727

avg / total       0.59      0.60      0.56     39882

In [110]:
a=[]
b=[]
for i in y_test:
    if(i==0):
        a.append(i)
    else:
        b.append(i)
print(len(a),len(b))

32007 7875

In [92]:
clf.fit(train_copy[X],y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [58]:
test=pd.read_csv('test_data .csv')

In [59]:
test.nunique()

id               3497
ad               2656
link             2869
timestamp       31830
grp               105
funnel_level        3
dtype: int64

In [60]:
test.shape

(49414, 6)

In [61]:
test_copy=test.copy()

In [62]:
def unique_values(column='abc'):
    df=pd.DataFrame()
    df=test_copy[column].value_counts().reset_index()
    if(len(df)>50):
        df.columns=[column,'count']
        df.to_csv('{}_count.csv'.format(column))
        print(column+'------Generated as csv')
        print(df.head(20))
    else:
        print(column+'unique value')
        print(df)
for i in list(test.columns):
    print(i)
    unique_values(i)

id
id------Generated as csv
                      id  count
0     session68719476737    194
1   session1451698946077    160
2   session1142461300815    148
3     session94489280611    123
4    session755914244115    116
5    session498216206378    108
6   session1683627180036    104
7   session1374389534771    102
8     session17179869219     99
9    session987842478117     96
10   session438086664211     95
11   session627065225289     92
12   session103079215178     88
13   session712964571219     87
14  session1614907703315     86
15   session876173328405     86
16   session893353197601     86
17   session395136991274     84
18  session1142461300749     84
19  session1159641170009     83
ad
ad------Generated as csv
                 ad  count
0    ad326417514499    201
1    ad446676598832    194
2    ad644245094406    151
3    ad695784701977    148
4    ad609885356045    114
5   ad1073741824010    114
6   ad1005022347301    104
7    ad240518168630    103
8    ad833223655441     92
9    ad609885356067     92
10  ad1477468749829     91
11  ad1666447310883     88
12   ad188978561038     88
13  ad1640677507105     87
14  ad1563368095769     85
15  ad1065151889436     83
16  ad1451698946059     81
17     ad8589934641     77
18   ad730144440325     77
19  ad1168231104520     76
link
link------Generated as csv
                 link  count
0    link798863917076   3683
1   link1288490188815   2910
2    link755914244118   2420
3    link532575944722   2415
4    link214748364811   2241
5   link1468878815250   1453
6    link996432412694    797
7     link25769803776    763
8   link1125281431562    759
9    link369367187470    651
10  link1194000908303    580
11   link257698037775    564
12   link627065225236    564
13  link1030792151065    559
14     link8589934595    498
15  link1288490188816    471
16   link395136991258    443
17   link824633720850    421
18    link34359738385    380
19  link1683627180045    366
timestamp
timestamp------Generated as csv
                        timestamp  count
0   2018-04-30T11:33:56.000-04:00     12
1   2018-04-30T15:26:46.000-04:00     11
2   2018-04-30T11:04:01.000-04:00     10
3   2018-04-30T21:08:18.000-04:00     10
4   2018-04-30T11:37:02.000-04:00     10
5   2018-04-30T11:57:10.000-04:00     10
6   2018-04-30T14:51:01.000-04:00     10
7   2018-04-30T10:50:30.000-04:00     10
8   2018-04-30T15:52:36.000-04:00     10
9   2018-04-30T11:17:16.000-04:00     10
10  2018-04-30T21:45:06.000-04:00      9
11  2018-04-30T14:33:26.000-04:00      9
12  2018-04-30T13:33:28.000-04:00      9
13  2018-04-30T14:40:02.000-04:00      9
14  2018-04-30T20:43:07.000-04:00      9
15  2018-04-30T15:32:54.000-04:00      9
16  2018-04-30T08:51:45.000-04:00      9
17  2018-04-30T10:32:17.000-04:00      9
18  2018-04-30T10:36:39.000-04:00      9
19  2018-04-30T22:05:11.000-04:00      9
grp
grp------Generated as csv
                 grp  count
0   grp1340029796352  22872
1   grp1511828488192   2711
2    grp936302870528   2435
3   grp1056561954816   2116
4    grp489626271744   1145
5   grp1108101562368   1074
6   grp1589137899520    944
7   grp1013612281856    907
8    grp644245094400    751
9    grp377957122048    739
10   grp670014898176    602
11   grp936302870529    596
12   grp111669149696    587
13   grp257698037760    543
14   grp687194767360    537
15   grp627065225216    483
16  grp1511828488193    465
17   grp987842478080    453
18   grp979252543488    407
19   grp704374636544    402
funnel_level
funnel_levelunique value
    index  funnel_level
0   upper         29515
1  middle         15236
2   lower          4663

In [63]:
def missing_data(df):
    df1=df.isna()
    for i in list(df.columns):
#         print(i)
#         print(df1[df1[i]==True])
        a=len(df1[df1[i]==True])
        if(a>0):
            print("the column with missing data",i)
            print("total missing data",len(df[df1[i]==True]))
            df[i]=df[i].fillna('noad')
            print(df)
    return df

test_copy=missing_data(test)

the column with missing data ad
total missing data 19848
                         id               ad               link  \
0       session240518168612   ad678604832787  link1288490188810
1       session876173328405  ad1451698946059  link1288490188810
2      session1382979469382  ad1468878815242  link1288490188810
3       session927712936010             ad64  link1288490188800
4       session970662608923    ad17179869199  link1288490188800
5       session678604832828    ad25769803834  link1288490188800
6       session876173328440    ad34359738386  link1288490188800
7       session919123001353    ad34359738421  link1288490188800
8      session1649267441740    ad34359738388  link1288490188800
9      session1357209665586    ad42949673007  link1288490188800
10     session1589137899611    ad60129542180  link1288490188800
11     session1434519076874    ad60129542188  link1288490188800
12     session1683627180088    ad68719476778  link1288490188800
13     session1099511627790    ad68719476791  link1288490188800
14     session1675037245493    ad68719476770  link1288490188800
15      session755914244109    ad85899345976  link1288490188800
16      session798863917140    ad94489280539  link1288490188800
17      session360777252897    ad94489280526  link1288490188800
18      session927712935963   ad103079215137  link1288490188800
19      session747324309529   ad103079215160  link1288490188800
20     session1563368095809   ad120259084309  link1288490188800
21      session953482739728   ad120259084295  link1288490188800
22     session1056561954889   ad128849018903  link1288490188800
23     session1468878815277   ad128849018881  link1288490188800
24       session77309411351   ad137438953499  link1288490188800
25     session1030792151093   ad146028888069  link1288490188800
26      session755914244104   ad154618822697  link1288490188800
27     session1657857376306   ad180388626460  link1288490188800
28      session764504178748   ad188978561037  link1288490188800
29     session1116691496975   ad197568495617  link1288490188800
...                     ...              ...                ...
49384   session223338299400  ad1133871366173   link455266533401
49385   session446676598823  ad1529008357387   link455266533392
49386  session1279900254260   ad412316860468   link455266533394
49387   session463856468016  ad1331439861793   link455266533391
49388  session1546188226637   ad893353197572  link1657857376269
49389  session1546188226637   ad893353197572  link1657857376269
49390   session970662608923    ad17179869199  link1657857376278
49391  session1675037245475   ad429496729634  link1657857376278
49392   session188978561064   ad326417514510  link1657857376279
49393  session1262720385072   ad438086664236  link1657857376256
49394  session1262720385072   ad438086664236  link1657857376256
49395   session420906795021   ad420906795069  link1657857376281
49396   session395136991281   ad558345748523  link1657857376281
49397    session85899346001  ad1262720385030  link1657857376281
49398  session1090921693218  ad1271310319669  link1657857376281
49399  session1090921693218  ad1271310319669  link1657857376281
49400  session1090921693218  ad1271310319669  link1657857376281
49401   session360777252879  ad1348619730951  link1657857376281
49402   session987842478117  ad1563368095769  link1657857376281
49403  session1494648619019             ad36  link1657857376260
49404    session25769803817             noad  link1657857376260
49405    session25769803817             noad  link1657857376260
49406  session1563368095804             noad  link1657857376260
49407  session1047972020234             noad  link1657857376259
49408  session1563368095804             noad  link1657857376259
49409  session1700807049279   ad695784701973  link1657857376265
49410  session1675037245469   ad326417514499  link1657857376275
49411   session867583393856  ad1254130450443  link1657857376272
49412   session549755813938             noad  link1657857376273
49413   session575525617674   ad687194767361  link1657857376273

                           timestamp               grp funnel_level
0      2018-04-30T16:55:51.000-04:00   grp936302870529        lower
1      2018-04-30T12:36:40.000-04:00   grp936302870529        lower
2      2018-04-30T20:20:44.000-04:00   grp936302870529        lower
3      2018-04-30T21:32:33.000-04:00   grp111669149696        lower
4      2018-04-30T15:49:45.000-04:00   grp111669149696        lower
5      2018-04-30T17:16:10.000-04:00   grp111669149696        lower
6      2018-04-30T19:11:31.000-04:00   grp111669149696        lower
7      2018-04-30T09:25:10.000-04:00   grp111669149696        lower
8      2018-04-30T21:56:23.000-04:00   grp111669149696        lower
9      2018-04-30T15:13:22.000-04:00   grp111669149696        lower
10     2018-04-30T22:15:15.000-04:00   grp111669149696        lower
11     2018-04-30T08:25:27.000-04:00   grp111669149696        lower
12     2018-04-30T16:04:52.000-04:00   grp111669149696        lower
13     2018-04-30T11:15:30.000-04:00   grp111669149696        lower
14     2018-04-30T17:09:44.000-04:00   grp111669149696        lower
15     2018-04-30T10:46:07.000-04:00   grp111669149696        lower
16     2018-04-30T22:41:28.000-04:00   grp111669149696        lower
17     2018-04-30T12:52:17.000-04:00   grp111669149696        lower
18     2018-04-30T12:16:12.000-04:00   grp111669149696        lower
19     2018-04-30T12:58:00.000-04:00   grp111669149696        lower
20     2018-04-30T16:59:48.000-04:00   grp111669149696        lower
21     2018-04-30T12:17:55.000-04:00   grp111669149696        lower
22     2018-04-30T17:54:02.000-04:00   grp111669149696        lower
23     2018-04-30T14:25:00.000-04:00   grp111669149696        lower
24     2018-04-30T12:12:40.000-04:00   grp111669149696        lower
25     2018-04-30T16:05:11.000-04:00   grp111669149696        lower
26     2018-04-30T09:46:39.000-04:00   grp111669149696        lower
27     2018-04-30T17:03:53.000-04:00   grp111669149696        lower
28     2018-04-30T18:08:38.000-04:00   grp111669149696        lower
29     2018-04-30T09:35:06.000-04:00   grp111669149696        lower
...                              ...               ...          ...
49384  2018-04-30T08:31:39.000-04:00  grp1649267441664        upper
49385  2018-04-30T13:46:34.000-04:00  grp1056561954816        upper
49386  2018-04-30T16:13:17.000-04:00  grp1056561954816        upper
49387  2018-04-30T20:23:55.000-04:00  grp1056561954816        upper
49388  2018-04-30T19:35:52.000-04:00  grp1013612281856       middle
49389  2018-04-30T19:36:21.000-04:00  grp1013612281856       middle
49390  2018-04-30T13:22:07.000-04:00  grp1511828488192       middle
49391  2018-04-30T13:05:52.000-04:00  grp1511828488192       middle
49392  2018-04-30T14:35:12.000-04:00  grp1511828488193       middle
49393  2018-04-30T16:14:21.000-04:00   grp257698037760       middle
49394  2018-04-30T16:14:21.000-04:00  grp1520418422784       middle
49395  2018-04-30T09:28:09.000-04:00  grp1589137899520       middle
49396  2018-04-30T15:50:48.000-04:00  grp1589137899520       middle
49397  2018-04-30T21:25:30.000-04:00  grp1589137899520       middle
49398  2018-04-30T15:06:13.000-04:00  grp1589137899520       middle
49399  2018-04-30T15:06:14.000-04:00  grp1589137899520       middle
49400  2018-04-30T15:06:20.000-04:00  grp1589137899520       middle
49401  2018-04-30T11:27:57.000-04:00  grp1589137899520       middle
49402  2018-04-30T12:18:48.000-04:00  grp1589137899520       middle
49403  2018-04-30T09:05:29.000-04:00   grp446676598784        upper
49404  2018-04-30T13:22:45.000-04:00   grp446676598784        upper
49405  2018-04-30T13:22:59.000-04:00   grp446676598784        upper
49406  2018-04-30T15:36:12.000-04:00   grp446676598784        upper
49407  2018-04-30T10:17:29.000-04:00   grp446676598784        upper
49408  2018-04-30T15:36:15.000-04:00   grp446676598784        upper
49409  2018-04-30T19:33:05.000-04:00   grp936302870528        upper
49410  2018-04-30T13:52:11.000-04:00  grp1340029796352        upper
49411  2018-04-30T18:07:11.000-04:00  grp1073741824000        upper
49412  2018-04-30T13:20:24.000-04:00  grp1254130450432        upper
49413  2018-04-30T09:30:04.000-04:00  grp1254130450432        upper

[49414 rows x 6 columns]

In [64]:
def encoding_label(column="abc"):
    if(column!='timestamp' and column!='checkout' and column!='order_placed'):
        try:
            var=0
            var = preprocessing.LabelEncoder()
            var.fit(test_copy[column])
            print(column)
            print(var.classes_)
            test_copy[column]=var.transform(test_copy[column])
            print(test_copy[column])
        except:
            print(column+' not done with label encoding - error')
    else:
        if(column=='timestamp'):
            print("timestamp is skipped")
        elif(column=='checkout'):
            print("checkout is not need")
        elif(column=='order_placed'):
            print("order_placed is not need")
            
for i in list(test.columns):
    encoding_label(i)

id
['session************' 'session1' 'session1005022347266' ...
 'session996432412726' 'session996432412735' 'session996432412742']
0        1728
1        3236
2         818
3        3344
4        3444
5        2765
6        3245
7        3317
8        1416
9         744
10       1281
11        901
12       1486
13        214
14       1472
15       2935
16       3056
17       2035
18       3335
19       2917
20       1215
21       3411
22        133
23       1002
24       2999
25         70
26       2933
27       1434
28       2974
29        244
         ...
49384    1683
49385    2221
49386     581
49387    2264
49388    1166
49389    1166
49390    3444
49391    1469
49392    1610
49393     551
49394     551
49395    2137
49396    2107
49397    3199
49398     200
49399     200
49400     200
49401    2032
49402    3472
49403    1048
49404    1776
49405    1776
49406    1213
49407     107
49408    1213
49409    1522
49410    1467
49411    3225
49412    2445
49413    2502
Name: id, Length: 49414, dtype: int64
ad
['ad************' 'ad1005022347267' 'ad1005022347270' ... 'ad996432412717'
 'ad996432412725' 'noad']
0        2088
1         764
2         811
3        2036
4        1246
5        1406
6        1560
7        1568
8        1561
9        1724
10       1978
11       1981
12       2117
13       2121
14       2114
15       2418
16       2567
17       2565
18         59
19         68
20        352
21        351
22        509
23        499
24        656
25        791
26        964
27       1257
28       1267
29       1285
         ...
49384     231
49385     913
49386    1690
49387     574
49388    2472
49389    2472
49390    1246
49391    1707
49392    1516
49393    1733
49394    1733
49395    1698
49396    1904
49397     450
49398     480
49399     480
49400     480
49401     602
49402     983
49403    1589
49404    2656
49405    2656
49406    2656
49407    2656
49408    2656
49409    2127
49410    1512
49411     429
49412    2656
49413    2097
Name: ad, Length: 49414, dtype: int64
link
['link************' 'link1' 'link10' ... 'link996432412699'
 'link996432412700' 'link996432412701']
0         529
1         529
2         529
3         523
4         523
5         523
6         523
7         523
8         523
9         523
10        523
11        523
12        523
13        523
14        523
15        523
16        523
17        523
18        523
19        523
20        523
21        523
22        523
23        523
24        523
25        523
26        523
27        523
28        523
29        523
         ...
49384    1844
49385    1840
49386    1841
49387    1839
49388    1236
49389    1236
49390    1240
49391    1240
49392    1241
49393    1232
49394    1232
49395    1242
49396    1242
49397    1242
49398    1242
49399    1242
49400    1242
49401    1242
49402    1242
49403    1234
49404    1234
49405    1234
49406    1234
49407    1233
49408    1233
49409    1235
49410    1239
49411    1237
49412    1238
49413    1238
Name: link, Length: 49414, dtype: int64
timestamp is skipped
grp
['grp0' 'grp1013612281856' 'grp1022202216448' 'grp1022202216449'
 'grp1039382085632' 'grp1047972020224' 'grp1056561954816'
 'grp1073741824000' 'grp1073741824001' 'grp1090921693184'
 'grp1108101562368' 'grp111669149696' 'grp1159641169920'
 'grp1194000908288' 'grp1245540515840' 'grp1254130450432'
 'grp1254130450433' 'grp1254130450434' 'grp1271310319616'
 'grp1279900254208' 'grp1279900254209' 'grp1279900254210'
 'grp128849018880' 'grp1297080123392' 'grp1314259992576'
 'grp1314259992577' 'grp1322849927168' 'grp1340029796352'
 'grp1357209665536' 'grp1357209665537' 'grp1357209665538'
 'grp1391569403904' 'grp1425929142272' 'grp1434519076864'
 'grp1434519076865' 'grp1443109011456' 'grp1468878815232'
 'grp1468878815233' 'grp1494648619008' 'grp1511828488192'
 'grp1511828488193' 'grp1520418422784' 'grp1529008357376'
 'grp1571958030336' 'grp1580547964928' 'grp1589137899520'
 'grp1606317768704' 'grp163208757248' 'grp1649267441664'
 'grp1666447310848' 'grp1709396983808' 'grp1709396983809' 'grp17179869184'
 'grp17179869185' 'grp180388626432' 'grp197568495616' 'grp206158430208'
 'grp214748364800' 'grp249108103168' 'grp257698037760' 'grp257698037761'
 'grp283467841536' 'grp309237645312' 'grp309237645313' 'grp317827579905'
 'grp317827579906' 'grp326417514496' 'grp34359738368' 'grp343597383680'
 'grp343597383681' 'grp369367187456' 'grp377957122048' 'grp429496729600'
 'grp438086664192' 'grp446676598784' 'grp463856467968' 'grp489626271744'
 'grp489626271745' 'grp489626271746' 'grp51539607552' 'grp523986010112'
 'grp566935683072' 'grp584115552256' 'grp601295421440' 'grp627065225216'
 'grp635655159808' 'grp644245094400' 'grp670014898176' 'grp687194767360'
 'grp704374636544' 'grp721554505728' 'grp738734374912' 'grp764504178688'
 'grp841813590016' 'grp85899345920' 'grp919123001344' 'grp927712935936'
 'grp936302870528' 'grp936302870529' 'grp94489280512' 'grp962072674304'
 'grp970662608896' 'grp979252543488' 'grp987842478080' 'grp996432412672']
0        98
1        98
2        98
3        11
4        11
5        11
6        11
7        11
8        11
9        11
10       11
11       11
12       11
13       11
14       11
15       11
16       11
17       11
18       11
19       11
20       11
21       11
22       11
23       11
24       11
25       11
26       11
27       11
28       11
29       11
         ..
49384    48
49385     6
49386     6
49387     6
49388     1
49389     1
49390    39
49391    39
49392    40
49393    59
49394    41
49395    45
49396    45
49397    45
49398    45
49399    45
49400    45
49401    45
49402    45
49403    74
49404    74
49405    74
49406    74
49407    74
49408    74
49409    97
49410    27
49411     7
49412    15
49413    15
Name: grp, Length: 49414, dtype: int64
funnel_level
['lower' 'middle' 'upper']
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
49384    2
49385    2
49386    2
49387    2
49388    1
49389    1
49390    1
49391    1
49392    1
49393    1
49394    1
49395    1
49396    1
49397    1
49398    1
49399    1
49400    1
49401    1
49402    1
49403    2
49404    2
49405    2
49406    2
49407    2
49408    2
49409    2
49410    2
49411    2
49412    2
49413    2
Name: funnel_level, Length: 49414, dtype: int64

In [65]:
test_copy

         id    ad  link                      timestamp  grp  funnel_level
0      1728  2088   529  2018-04-30T16:55:51.000-04:00   98             0
1      3236   764   529  2018-04-30T12:36:40.000-04:00   98             0
2       818   811   529  2018-04-30T20:20:44.000-04:00   98             0
3      3344  2036   523  2018-04-30T21:32:33.000-04:00   11             0
4      3444  1246   523  2018-04-30T15:49:45.000-04:00   11             0
5      2765  1406   523  2018-04-30T17:16:10.000-04:00   11             0
6      3245  1560   523  2018-04-30T19:11:31.000-04:00   11             0
7      3317  1568   523  2018-04-30T09:25:10.000-04:00   11             0
8      1416  1561   523  2018-04-30T21:56:23.000-04:00   11             0
9       744  1724   523  2018-04-30T15:13:22.000-04:00   11             0
10     1281  1978   523  2018-04-30T22:15:15.000-04:00   11             0
11      901  1981   523  2018-04-30T08:25:27.000-04:00   11             0
12     1486  2117   523  2018-04-30T16:04:52.000-04:00   11             0
13      214  2121   523  2018-04-30T11:15:30.000-04:00   11             0
14     1472  2114   523  2018-04-30T17:09:44.000-04:00   11             0
15     2935  2418   523  2018-04-30T10:46:07.000-04:00   11             0
16     3056  2567   523  2018-04-30T22:41:28.000-04:00   11             0
17     2035  2565   523  2018-04-30T12:52:17.000-04:00   11             0
18     3335    59   523  2018-04-30T12:16:12.000-04:00   11             0
19     2917    68   523  2018-04-30T12:58:00.000-04:00   11             0
20     1215   352   523  2018-04-30T16:59:48.000-04:00   11             0
21     3411   351   523  2018-04-30T12:17:55.000-04:00   11             0
22      133   509   523  2018-04-30T17:54:02.000-04:00   11             0
23     1002   499   523  2018-04-30T14:25:00.000-04:00   11             0
24     2999   656   523  2018-04-30T12:12:40.000-04:00   11             0
25       70   791   523  2018-04-30T16:05:11.000-04:00   11             0
26     2933   964   523  2018-04-30T09:46:39.000-04:00   11             0
27     1434  1257   523  2018-04-30T17:03:53.000-04:00   11             0
28     2974  1267   523  2018-04-30T18:08:38.000-04:00   11             0
29      244  1285   523  2018-04-30T09:35:06.000-04:00   11             0
...     ...   ...   ...                            ...  ...           ...
49384  1683   231  1844  2018-04-30T08:31:39.000-04:00   48             2
49385  2221   913  1840  2018-04-30T13:46:34.000-04:00    6             2
49386   581  1690  1841  2018-04-30T16:13:17.000-04:00    6             2
49387  2264   574  1839  2018-04-30T20:23:55.000-04:00    6             2
49388  1166  2472  1236  2018-04-30T19:35:52.000-04:00    1             1
49389  1166  2472  1236  2018-04-30T19:36:21.000-04:00    1             1
49390  3444  1246  1240  2018-04-30T13:22:07.000-04:00   39             1
49391  1469  1707  1240  2018-04-30T13:05:52.000-04:00   39             1
49392  1610  1516  1241  2018-04-30T14:35:12.000-04:00   40             1
49393   551  1733  1232  2018-04-30T16:14:21.000-04:00   59             1
49394   551  1733  1232  2018-04-30T16:14:21.000-04:00   41             1
49395  2137  1698  1242  2018-04-30T09:28:09.000-04:00   45             1
49396  2107  1904  1242  2018-04-30T15:50:48.000-04:00   45             1
49397  3199   450  1242  2018-04-30T21:25:30.000-04:00   45             1
49398   200   480  1242  2018-04-30T15:06:13.000-04:00   45             1
49399   200   480  1242  2018-04-30T15:06:14.000-04:00   45             1
49400   200   480  1242  2018-04-30T15:06:20.000-04:00   45             1
49401  2032   602  1242  2018-04-30T11:27:57.000-04:00   45             1
49402  3472   983  1242  2018-04-30T12:18:48.000-04:00   45             1
49403  1048  1589  1234  2018-04-30T09:05:29.000-04:00   74             2
49404  1776  2656  1234  2018-04-30T13:22:45.000-04:00   74             2
49405  1776  2656  1234  2018-04-30T13:22:59.000-04:00   74             2
49406  1213  2656  1234  2018-04-30T15:36:12.000-04:00   74             2
49407   107  2656  1233  2018-04-30T10:17:29.000-04:00   74             2
49408  1213  2656  1233  2018-04-30T15:36:15.000-04:00   74             2
49409  1522  2127  1235  2018-04-30T19:33:05.000-04:00   97             2
49410  1467  1512  1239  2018-04-30T13:52:11.000-04:00   27             2
49411  3225   429  1237  2018-04-30T18:07:11.000-04:00    7             2
49412  2445  2656  1238  2018-04-30T13:20:24.000-04:00   15             2
49413  2502  2097  1238  2018-04-30T09:30:04.000-04:00   15             2

[49414 rows x 6 columns]

In [66]:
a=[]
for i in test_copy['timestamp']:
#     i=str(i)
    i=i.replace(i[0:11],'')
    i=i.replace('.000-04:00','')
    a.append(i)

In [67]:
a

['16:55:51',
 '12:36:40',
 '20:20:44',
 '21:32:33',
 '15:49:45',
 '17:16:10',
 '19:11:31',
 '09:25:10',
 '21:56:23',
 '15:13:22',
 '22:15:15',
 '08:25:27',
 '16:04:52',
 '11:15:30',
 '17:09:44',
 '10:46:07',
 '22:41:28',
 '12:52:17',
 '12:16:12',
 '12:58:00',
 '16:59:48',
 '12:17:55',
 '17:54:02',
 '14:25:00',
 '12:12:40',
 '16:05:11',
 '09:46:39',
 '17:03:53',
 '18:08:38',
 '09:35:06',
 '19:04:09',
 '07:44:16',
 '13:45:25',
 '06:26:18',
 '17:25:01',
 '11:01:46',
 '10:52:20',
 '20:48:00',
 '20:13:07',
 '21:13:14',
 '06:50:27',
 '19:03:58',
 '18:39:15',
 '09:33:08',
 '17:25:08',
 '20:03:58',
 '10:15:16',
 '14:06:44',
 '21:32:36',
 '19:23:48',
 '13:24:43',
 '13:55:01',
 '14:46:14',
 '21:42:23',
 '10:29:44',
 '09:37:39',
 '15:44:13',
 '10:26:38',
 '14:56:26',
 '15:31:40',
 '22:42:23',
 '07:08:58',
 '00:36:29',
 '21:10:33',
 '14:01:53',
 '15:09:02',
 '11:06:04',
 '20:57:17',
 '19:23:54',
 '14:37:45',
 '12:06:48',
 '16:04:25',
 '18:45:27',
 '00:30:10',
 '15:55:44',
 '14:10:43',
 '23:14:27',
 '09:33:26',
 '09:40:25',
 '23:56:46',
 '09:58:46',
 '15:19:31',
 '17:05:59',
 '16:58:30',
 '13:35:26',
 '14:33:34',
 '20:08:49',
 '09:10:27',
 '21:04:24',
 '22:51:54',
 '22:16:49',
 '21:36:18',
 '16:41:25',
 '17:55:53',
 '09:53:47',
 '15:57:16',
 '13:31:48',
 '10:43:56',
 '13:21:46',
 '20:10:39',
 '19:44:59',
 '20:31:38',
 '21:23:24',
 '11:47:34',
 '15:19:42',
 '15:31:12',
 '17:08:48',
 '10:43:49',
 '17:00:24',
 '10:50:09',
 '18:43:29',
 '09:26:38',
 '22:56:06',
 '23:17:58',
 '12:20:48',
 '14:06:10',
 '22:11:55',
 '12:58:20',
 '09:41:41',
 '11:25:27',
 '22:53:01',
 '12:58:22',
 '19:37:17',
 '18:27:25',
 '16:08:30',
 '13:15:22',
 '21:44:42',
 '11:54:32',
 '12:08:27',
 '22:41:27',
 '20:11:17',
 '14:36:22',
 '11:06:22',
 '10:17:48',
 '11:45:06',
 '15:59:40',
 '14:06:43',
 '11:02:36',
 '21:44:51',
 '09:03:44',
 '16:15:40',
 '22:11:29',
 '11:13:09',
 '10:03:52',
 '19:43:43',
 '14:51:31',
 '23:11:39',
 '11:25:40',
 '13:13:48',
 '12:41:13',
 '16:42:09',
 '22:03:19',
 '00:06:35',
 '17:31:37',
 '21:39:40',
 '12:40:28',
 '20:53:51',
 '22:56:27',
 '11:39:08',
 '17:30:49',
 '18:09:26',
 '21:11:06',
 '09:49:20',
 '13:44:48',
 '22:27:45',
 '13:04:43',
 '11:34:58',
 '09:49:29',
 '12:40:27',
 '07:58:11',
 '17:46:42',
 '18:16:15',
 '15:15:41',
 '15:52:41',
 '13:56:48',
 '19:52:39',
 '19:57:57',
 '20:51:54',
 '12:48:00',
 '09:35:02',
 '13:55:16',
 '15:08:52',
 '22:12:13',
 '21:28:08',
 '22:08:06',
 '09:50:33',
 '15:41:55',
 '08:25:32',
 '13:43:08',
 '20:11:01',
 '22:10:43',
 '05:31:20',
 '07:56:02',
 '16:06:31',
 '19:16:04',
 '21:21:43',
 '10:51:38',
 '21:36:56',
 '18:03:43',
 '15:14:21',
 '15:17:27',
 '20:45:33',
 '23:21:50',
 '17:06:27',
 '10:27:23',
 '17:59:09',
 '11:51:52',
 '11:52:03',
 '11:52:20',
 '16:47:07',
 '17:04:09',
 '23:18:06',
 '18:35:29',
 '18:35:31',
 '14:23:49',
 '22:06:13',
 '22:06:35',
 '23:00:19',
 '23:13:54',
 '23:13:56',
 '23:14:09',
 '16:34:39',
 '16:36:43',
 '04:49:19',
 '01:00:11',
 '01:00:14',
 '12:32:55',
 '11:49:49',
 '21:05:13',
 '11:58:23',
 '12:22:15',
 '10:29:17',
 '21:46:03',
 '14:42:31',
 '18:18:43',
 '18:19:41',
 '11:45:33',
 '12:21:37',
 '10:55:25',
 '17:54:13',
 '22:24:43',
 '07:03:40',
 '14:25:59',
 '11:35:46',
 '19:28:52',
 '15:03:23',
 '20:38:08',
 '14:09:55',
 '18:14:30',
 '00:23:53',
 '01:04:04',
 '13:11:19',
 '14:18:12',
 '15:59:30',
 '22:56:50',
 '11:00:33',
 '15:46:28',
 '18:53:56',
 '11:13:03',
 '11:57:51',
 '11:59:18',
 '13:23:39',
 '15:26:42',
 '12:55:37',
 '16:45:43',
 '15:24:05',
 '13:37:58',
 '12:01:03',
 '23:02:35',
 '11:05:25',
 '21:18:11',
 '16:59:53',
 '15:42:40',
 '21:23:06',
 '10:58:42',
 '11:07:57',
 '11:17:15',
 '21:23:40',
 '13:47:10',
 '21:21:36',
 '18:05:50',
 '18:08:14',
 '12:46:46',
 '10:31:43',
 '14:26:01',
 '14:26:14',
 '14:37:04',
 '15:47:33',
 '13:46:25',
 '10:10:28',
 '23:21:01',
 '13:15:20',
 '12:30:53',
 '18:28:33',
 '21:46:25',
 '15:33:44',
 '15:34:50',
 '12:59:22',
 '00:20:23',
 '09:36:39',
 '10:17:57',
 '17:58:33',
 '10:10:06',
 '21:30:33',
 '20:47:05',
 '01:34:18',
 '16:04:41',
 '12:57:36',
 '09:54:46',
 '12:49:52',
 '13:04:40',
 '09:59:18',
 '11:16:47',
 '16:33:09',
 '00:41:21',
 '16:02:07',
 '16:03:04',
 '22:46:16',
 '19:53:00',
 '17:09:53',
 '17:58:49',
 '14:16:09',
 '20:08:18',
 '22:45:23',
 '18:38:13',
 '10:37:59',
 '13:42:40',
 '20:41:26',
 '15:29:39',
 '00:13:18',
 '18:25:23',
 '12:33:49',
 '06:00:43',
 '13:53:32',
 '09:17:46',
 '11:23:11',
 '17:14:06',
 '20:28:01',
 '17:04:36',
 '21:32:26',
 '08:59:38',
 '12:45:26',
 '21:03:00',
 '11:40:16',
 '07:58:53',
 '14:49:26',
 '14:49:58',
 '16:14:21',
 '15:22:21',
 '15:24:35',
 '15:47:08',
 '15:36:50',
 '05:44:08',
 '14:14:29',
 '23:54:07',
 '00:23:49',
 '22:58:38',
 '13:54:22',
 '11:27:48',
 '16:07:10',
 '18:52:14',
 '16:31:08',
 '18:15:51',
 '20:43:03',
 '08:35:53',
 '09:43:52',
 '16:43:43',
 '21:07:38',
 '10:42:00',
 '18:32:10',
 '18:32:28',
 '23:22:29',
 '12:40:54',
 '18:25:47',
 '00:36:51',
 '22:54:00',
 '18:35:33',
 '16:56:28',
 '03:37:29',
 '11:51:45',
 '12:32:07',
 '04:45:53',
 '04:46:40',
 '22:06:06',
 '09:52:35',
 '15:28:08',
 '12:20:47',
 '12:20:59',
 '17:15:02',
 '08:08:54',
 '15:04:44',
 '10:10:26',
 '14:39:41',
 '21:23:42',
 '19:36:14',
 '19:31:41',
 '19:31:48',
 '09:47:10',
 '09:50:52',
 '13:41:09',
 '13:00:45',
 '20:18:21',
 '08:03:53',
 '14:51:50',
 '13:02:50',
 '13:31:05',
 '17:13:11',
 '13:04:09',
 '13:57:58',
 '14:24:03',
 '14:05:58',
 '20:36:51',
 '16:32:54',
 '16:41:04',
 '21:33:06',
 '13:31:00',
 '23:30:16',
 '17:04:16',
 '16:16:46',
 '05:12:49',
 '11:41:58',
 '23:52:01',
 '09:54:06',
 '11:52:12',
 '13:29:59',
 '23:10:22',
 '15:32:58',
 '13:45:11',
 '12:39:23',
 '23:23:19',
 '15:22:36',
 '15:25:24',
 '21:25:36',
 '21:25:45',
 '21:25:52',
 '10:28:32',
 '12:05:44',
 '13:21:00',
 '13:45:05',
 '12:48:02',
 '14:05:06',
 '10:42:02',
 '15:01:34',
 '18:23:28',
 '10:44:05',
 '19:05:35',
 '17:21:55',
 '17:23:16',
 '14:04:40',
 '12:33:26',
 '19:35:29',
 '20:24:45',
 '19:58:11',
 '12:51:54',
 '20:53:01',
 '23:22:38',
 '23:34:04',
 '12:37:28',
 '13:03:31',
 '12:00:08',
 '09:26:03',
 '21:24:25',
 '08:18:31',
 '15:49:54',
 '13:21:36',
 '17:38:05',
 '18:05:37',
 '08:27:35',
 '08:27:57',
 '10:49:21',
 '10:17:47',
 '14:28:16',
 '09:27:31',
 '06:03:23',
 '11:43:06',
 '16:15:23',
 '06:51:27',
 '10:36:25',
 '15:07:42',
 '14:53:53',
 '09:07:51',
 '14:51:48',
 '11:48:57',
 '11:49:19',
 '22:39:06',
 '16:37:21',
 '06:33:20',
 '14:39:38',
 '14:41:47',
 '11:21:27',
 '11:29:39',
 '17:02:30',
 '17:06:11',
 '17:10:49',
 '20:40:32',
 '20:41:15',
 '11:35:57',
 '19:55:46',
 '20:06:27',
 '20:07:36',
 '11:19:30',
 '11:19:31',
 '11:19:47',
 '09:02:31',
 '22:06:23',
 '12:17:12',
 '20:43:26',
 '00:41:48',
 '10:23:12',
 '14:21:17',
 '08:21:10',
 '17:26:16',
 '17:39:49',
 '18:23:58',
 '02:17:41',
 '02:18:29',
 '11:48:43',
 '12:22:20',
 '18:30:33',
 '10:15:39',
 '00:13:30',
 '09:32:09',
 '14:08:02',
 '16:12:25',
 '19:02:34',
 '17:44:44',
 '21:00:30',
 '21:00:45',
 '19:55:41',
 '15:18:59',
 '16:09:23',
 '16:58:52',
 '00:23:39',
 '12:06:44',
 '07:00:18',
 '14:41:55',
 '06:20:58',
 '22:47:47',
 '13:03:14',
 '11:07:51',
 '15:42:45',
 '10:37:41',
 '17:36:11',
 '09:21:30',
 '11:57:08',
 '09:14:02',
 '09:17:08',
 '09:18:22',
 '21:38:55',
 '12:25:29',
 '20:30:37',
 '14:54:39',
 '15:41:41',
 '19:42:46',
 '10:33:57',
 '16:44:34',
 '13:57:57',
 '10:46:21',
 '11:46:26',
 '14:00:10',
 '14:55:24',
 '12:38:05',
 '16:30:13',
 '18:00:00',
 '15:37:52',
 '19:22:12',
 '01:04:01',
 '17:43:45',
 '13:56:40',
 '13:57:39',
 '12:30:11',
 '10:31:58',
 '12:12:53',
 '12:07:06',
 '14:26:13',
 '18:55:14',
 '15:28:12',
 '10:32:59',
 '16:52:25',
 '21:30:20',
 '21:58:12',
 '23:01:18',
 '10:26:22',
 '00:49:08',
 '15:16:21',
 '16:50:33',
 '09:44:10',
 '16:21:54',
 '16:21:57',
 '14:08:39',
 '15:37:00',
 '20:43:01',
 '17:04:20',
 '09:32:35',
 '09:19:38',
 '00:10:16',
 '13:18:23',
 '14:19:52',
 '19:56:47',
 '14:09:44',
 '09:23:51',
 '12:54:56',
 '20:03:12',
 '19:52:31',
 '07:48:25',
 '10:34:44',
 '09:33:57',
 '20:47:32',
 '09:51:55',
 '12:05:55',
 '14:42:28',
 '16:50:38',
 '11:27:54',
 '01:52:16',
 '09:40:13',
 '19:53:00',
 '14:37:54',
 '09:40:50',
 '10:31:28',
 '13:15:25',
 '19:39:53',
 '14:50:49',
 '15:42:49',
 '15:31:17',
 '14:03:06',
 '14:11:21',
 '08:47:39',
 '22:33:15',
 '13:35:24',
 '18:46:05',
 '22:16:10',
 '14:47:53',
 '18:10:22',
 '09:47:00',
 '13:14:49',
 '11:00:49',
 '18:08:02',
 '17:15:33',
 '08:53:15',
 '01:03:20',
 '18:21:14',
 '16:53:36',
 '10:00:15',
 '22:49:34',
 '14:41:32',
 '00:20:49',
 '21:23:25',
 '10:19:21',
 '10:21:59',
 '17:18:44',
 '23:15:46',
 '17:00:45',
 '20:17:02',
 '11:29:34',
 '11:32:41',
 '21:54:07',
 '11:47:13',
 '20:20:22',
 '11:56:26',
 '13:31:56',
 '20:51:31',
 '09:54:21',
 '10:16:08',
 '11:56:19',
 '20:13:39',
 '20:42:49',
 '09:23:07',
 '10:53:14',
 '20:51:04',
 '00:10:51',
 '12:28:25',
 '15:01:33',
 '23:46:21',
 '09:20:54',
 '09:21:39',
 '13:15:49',
 '13:31:30',
 '12:39:58',
 '22:49:26',
 '13:09:18',
 '12:05:37',
 '17:20:23',
 '17:21:07',
 '18:33:26',
 '10:41:56',
 '11:03:19',
 '15:06:44',
 '13:28:46',
 '13:33:01',
 '12:10:22',
 '08:09:10',
 '17:05:34',
 '13:01:45',
 '14:54:27',
 '10:46:02',
 '15:21:41',
 '13:58:48',
 '14:41:14',
 '20:24:56',
 '22:17:28',
 '23:27:21',
 '11:39:03',
 '08:16:12',
 '17:40:02',
 '23:18:46',
 '14:42:22',
 '13:14:33',
 '16:07:24',
 '12:57:53',
 '11:45:05',
 '11:37:56',
 '11:38:04',
 '15:59:29',
 '10:35:26',
 '12:21:28',
 '15:34:34',
 '10:55:10',
 '21:27:02',
 '17:54:00',
 '14:58:39',
 '13:20:32',
 '22:24:03',
 '07:03:27',
 '19:24:37',
 '20:56:31',
 '20:58:33',
 '08:06:14',
 '14:28:08',
 '22:06:23',
 '16:54:27',
 '20:33:04',
 '11:57:15',
 '11:35:37',
 '10:54:29',
 '06:16:36',
 '11:33:30',
 '19:28:44',
 '18:53:26',
 '09:15:41',
 '11:24:58',
 '13:57:32',
 '13:09:15',
 '15:03:16',
 '20:37:57',
 '16:50:00',
 '00:48:12',
 '11:28:35',
 '18:44:48',
 '01:22:35',
 '15:57:27',
 '09:48:26',
 '09:48:58',
 '13:48:29',
 '11:19:49',
 '18:05:49',
 '18:05:55',
 '02:39:39',
 '14:09:46',
 '12:49:29',
 '16:18:00',
 '16:20:23',
 '18:14:21',
 '20:01:04',
 '20:23:53',
 '00:23:40',
 '01:03:46',
 '13:10:55',
 '14:18:01',
 '16:35:09',
 '01:43:56',
 '19:40:13',
 '15:23:58',
 '22:46:16',
 '11:36:06',
 '16:30:43',
 '15:19:54',
 '15:52:28',
 '21:41:21',
 '13:46:44',
 '06:08:00',
 '14:54:36',
 '16:57:55',
 '08:25:57',
 '18:32:24',
 '14:10:30',
 '16:46:10',
 '15:35:13',
 '15:59:13',
 '10:05:27',
 '17:24:29',
 '13:05:43',
 '22:56:27',
 '01:05:41',
 '21:09:46',
 '21:12:04',
 '20:58:36',
 '09:14:50',
 '09:32:13',
 '09:00:38',
 '12:12:16',
 '17:07:32',
 '18:47:39',
 '18:48:43',
 '10:31:33',
 '18:24:30',
 '16:46:03',
 '16:49:38',
 '11:24:37',
 '16:23:04',
 '14:23:00',
 '14:24:10',
 '02:52:16',
 '06:39:58',
 '10:56:43',
 '20:44:47',
 '11:12:54',
 '11:13:33',
 '04:09:12',
 '19:20:40',
 '19:58:27',
 '19:22:48',
 '14:32:25',
 '15:39:59',
 '07:29:50',
 '11:00:21',
 '18:57:17',
 '11:10:33',
 '15:46:19',
 '07:00:40',
 '17:13:17',
 '11:45:17',
 '18:46:12',
 '13:26:00',
 '17:01:34',
 '18:10:25',
 '13:21:51',
 '18:53:43',
 '14:04:10',
 '11:12:52',
 '11:57:43',
 '11:59:09',
 '12:33:43',
 '12:56:43',
 '20:40:05',
 '23:54:38',
 '15:22:38',
 '01:13:14',
 '12:31:00',
 '07:30:47',
 '13:23:27',
 '16:04:18',
 '19:48:31',
 '15:26:24',
 '12:55:29',
 '01:30:08',
 '09:51:39',
 '15:20:13',
 '20:14:58',
 '16:45:32',
 '15:23:52',
 '03:47:26',
 '22:53:52',
 '20:12:40',
 '13:37:51',
 '14:44:00',
 '17:33:07',
 '14:19:37',
 '14:20:33',
 '12:00:12',
 '15:21:43',
 '12:01:10',
 '17:03:40',
 '20:09:13',
 '15:29:52',
 '14:08:58',
 '20:16:38',
 '11:17:17',
 '14:12:22',
 '10:40:29',
 '18:54:51',
 '18:57:37',
 '21:47:27',
 '08:18:38',
 '23:02:13',
 '10:39:04',
 '20:50:16',
 '03:51:02',
 '10:18:01',
 '13:57:52',
 '13:23:31',
 '10:02:59',
 '11:05:00',
 '21:17:53',
 '16:59:43',
 '11:30:46',
 '11:37:11',
 '16:25:23',
 '12:27:42',
 '23:02:54',
 '14:49:50',
 '16:16:00',
 '16:17:48',
 '11:15:04',
 '17:55:46',
 '16:44:09',
 '16:47:30',
 '15:42:33',
 '19:58:29',
 '20:00:20',
 '09:42:08',
 '21:22:59',
 '07:46:10',
 '17:04:35',
 '11:05:06',
 '16:08:21',
 '13:55:19',
 '10:58:29',
 '16:06:29',
 '18:59:16',
 '13:04:16',
 '23:41:45',
 '08:14:32',
 '16:44:32',
 '16:45:46',
 '16:47:28',
 '11:07:32',
 '16:23:40',
 '21:35:29',
 '14:43:19',
 '05:10:53',
 '23:27:10',
 '11:05:53',
 '11:06:17',
 '11:14:39',
 '11:17:03',
 '10:33:35',
 '10:42:58',
 '15:17:16',
 '21:23:30',
 '16:38:45',
 '13:46:58',
 '14:34:12',
 '21:21:24',
 '02:24:36',
 '22:05:57',
 '21:28:47',
 '18:02:54',
 '22:35:24',
 '18:05:25',
 '18:08:01',
 '08:49:25',
 '12:46:28',
 '19:48:40',
 '12:17:17',
 '10:31:22',
 '21:10:25',
 '10:38:46',
 '22:42:09',
 '00:46:10',
 '20:02:05',
 '20:02:55',
 '20:03:20',
 '00:10:12',
 '04:21:10',
 '15:38:37',
 '14:06:22',
 '18:36:56',
 '15:48:58',
 '10:29:52',
 '13:02:11',
 '09:54:33',
 '17:24:12',
 '17:24:38',
 '12:30:34',
 '14:25:21',
 '14:36:57',
 '13:14:14',
 '18:58:15',
 '05:19:45',
 '05:26:47',
 '18:48:10',
 '10:12:26',
 '02:00:04',
 '15:47:25',
 '19:54:06',
 '00:18:35',
 '16:22:29',
 '10:10:43',
 '13:46:13',
 '12:10:32',
 '17:55:44',
 '17:56:11',
 '13:55:38',
 '13:55:50',
 '16:16:23',
 '09:49:51',
 '10:10:13',
 '15:31:48',
 '15:32:00',
 '15:04:26',
 ...]

In [68]:
test_copy['timestamp']=a

In [69]:
test_copy

         id    ad  link timestamp  grp  funnel_level
0      1728  2088   529  16:55:51   98             0
1      3236   764   529  12:36:40   98             0
2       818   811   529  20:20:44   98             0
3      3344  2036   523  21:32:33   11             0
4      3444  1246   523  15:49:45   11             0
5      2765  1406   523  17:16:10   11             0
6      3245  1560   523  19:11:31   11             0
7      3317  1568   523  09:25:10   11             0
8      1416  1561   523  21:56:23   11             0
9       744  1724   523  15:13:22   11             0
10     1281  1978   523  22:15:15   11             0
11      901  1981   523  08:25:27   11             0
12     1486  2117   523  16:04:52   11             0
13      214  2121   523  11:15:30   11             0
14     1472  2114   523  17:09:44   11             0
15     2935  2418   523  10:46:07   11             0
16     3056  2567   523  22:41:28   11             0
17     2035  2565   523  12:52:17   11             0
18     3335    59   523  12:16:12   11             0
19     2917    68   523  12:58:00   11             0
20     1215   352   523  16:59:48   11             0
21     3411   351   523  12:17:55   11             0
22      133   509   523  17:54:02   11             0
23     1002   499   523  14:25:00   11             0
24     2999   656   523  12:12:40   11             0
25       70   791   523  16:05:11   11             0
26     2933   964   523  09:46:39   11             0
27     1434  1257   523  17:03:53   11             0
28     2974  1267   523  18:08:38   11             0
29      244  1285   523  09:35:06   11             0
...     ...   ...   ...       ...  ...           ...
49384  1683   231  1844  08:31:39   48             2
49385  2221   913  1840  13:46:34    6             2
49386   581  1690  1841  16:13:17    6             2
49387  2264   574  1839  20:23:55    6             2
49388  1166  2472  1236  19:35:52    1             1
49389  1166  2472  1236  19:36:21    1             1
49390  3444  1246  1240  13:22:07   39             1
49391  1469  1707  1240  13:05:52   39             1
49392  1610  1516  1241  14:35:12   40             1
49393   551  1733  1232  16:14:21   59             1
49394   551  1733  1232  16:14:21   41             1
49395  2137  1698  1242  09:28:09   45             1
49396  2107  1904  1242  15:50:48   45             1
49397  3199   450  1242  21:25:30   45             1
49398   200   480  1242  15:06:13   45             1
49399   200   480  1242  15:06:14   45             1
49400   200   480  1242  15:06:20   45             1
49401  2032   602  1242  11:27:57   45             1
49402  3472   983  1242  12:18:48   45             1
49403  1048  1589  1234  09:05:29   74             2
49404  1776  2656  1234  13:22:45   74             2
49405  1776  2656  1234  13:22:59   74             2
49406  1213  2656  1234  15:36:12   74             2
49407   107  2656  1233  10:17:29   74             2
49408  1213  2656  1233  15:36:15   74             2
49409  1522  2127  1235  19:33:05   97             2
49410  1467  1512  1239  13:52:11   27             2
49411  3225   429  1237  18:07:11    7             2
49412  2445  2656  1238  13:20:24   15             2
49413  2502  2097  1238  09:30:04   15             2

[49414 rows x 6 columns]

In [70]:
l=[]
def get_sec(time_str):
    for i in time_str:
        h, m, s = i.split(':')
        l.append(int(h) * 3600 + int(m) * 60 + int(s))
    return l
a=get_sec(test_copy['timestamp'])

In [71]:
a

[60951,
 45400,
 73244,
 77553,
 56985,
 62170,
 69091,
 33910,
 78983,
 54802,
 80115,
 30327,
 57892,
 40530,
 61784,
 38767,
 81688,
 46337,
 44172,
 46680,
 61188,
 44275,
 64442,
 51900,
 43960,
 57911,
 35199,
 61433,
 65318,
 34506,
 68649,
 27856,
 49525,
 23178,
 62701,
 39706,
 39140,
 74880,
 72787,
 76394,
 24627,
 68638,
 67155,
 34388,
 62708,
 72238,
 36916,
 50804,
 77556,
 69828,
 48283,
 50101,
 53174,
 78143,
 37784,
 34659,
 56653,
 37598,
 53786,
 55900,
 81743,
 25738,
 2189,
 76233,
 50513,
 54542,
 39964,
 75437,
 69834,
 52665,
 43608,
 57865,
 67527,
 1810,
 57344,
 51043,
 83667,
 34406,
 34825,
 86206,
 35926,
 55171,
 61559,
 61110,
 48926,
 52414,
 72529,
 33027,
 75864,
 82314,
 80209,
 77778,
 60085,
 64553,
 35627,
 57436,
 48708,
 38636,
 48106,
 72639,
 71099,
 73898,
 77004,
 42454,
 55182,
 55872,
 61728,
 38629,
 61224,
 39009,
 67409,
 33998,
 82566,
 83878,
 44448,
 50770,
 79915,
 46700,
 34901,
 41127,
 82381,
 46702,
 70637,
 66445,
 58110,
 47722,
 78282,
 42872,
 43707,
 81687,
 72677,
 52582,
 39982,
 37068,
 42306,
 57580,
 50803,
 39756,
 78291,
 32624,
 58540,
 79889,
 40389,
 36232,
 71023,
 53491,
 83499,
 41140,
 47628,
 45673,
 60129,
 79399,
 395,
 63097,
 77980,
 45628,
 75231,
 82587,
 41948,
 63049,
 65366,
 76266,
 35360,
 49488,
 80865,
 47083,
 41698,
 35369,
 45627,
 28691,
 64002,
 65775,
 54941,
 57161,
 50208,
 71559,
 71877,
 75114,
 46080,
 34502,
 50116,
 54532,
 79933,
 77288,
 79686,
 35433,
 56515,
 30332,
 49388,
 72661,
 79843,
 19880,
 28562,
 57991,
 69364,
 76903,
 39098,
 77816,
 65023,
 54861,
 55047,
 74733,
 84110,
 61587,
 37643,
 64749,
 42712,
 42723,
 42740,
 60427,
 61449,
 83886,
 66929,
 66931,
 51829,
 79573,
 79595,
 82819,
 83634,
 83636,
 83649,
 59679,
 59803,
 17359,
 3611,
 3614,
 45175,
 42589,
 75913,
 43103,
 44535,
 37757,
 78363,
 52951,
 65923,
 65981,
 42333,
 44497,
 39325,
 64453,
 80683,
 25420,
 51959,
 41746,
 70132,
 54203,
 74288,
 50995,
 65670,
 1433,
 3844,
 47479,
 51492,
 57570,
 82610,
 39633,
 56788,
 68036,
 40383,
 43071,
 43158,
 48219,
 55602,
 46537,
 60343,
 55445,
 49078,
 43263,
 82955,
 39925,
 76691,
 61193,
 56560,
 76986,
 39522,
 40077,
 40635,
 77020,
 49630,
 76896,
 65150,
 65294,
 46006,
 37903,
 51961,
 51974,
 52624,
 56853,
 49585,
 36628,
 84061,
 47720,
 45053,
 66513,
 78385,
 56024,
 56090,
 46762,
 1223,
 34599,
 37077,
 64713,
 36606,
 77433,
 74825,
 5658,
 57881,
 46656,
 35686,
 46192,
 47080,
 35958,
 40607,
 59589,
 2481,
 57727,
 57784,
 81976,
 71580,
 61793,
 64729,
 51369,
 72498,
 81923,
 67093,
 38279,
 49360,
 74486,
 55779,
 798,
 66323,
 45229,
 21643,
 50012,
 33466,
 40991,
 62046,
 73681,
 61476,
 77546,
 32378,
 45926,
 75780,
 42016,
 28733,
 53366,
 53398,
 58461,
 55341,
 55475,
 56828,
 56210,
 20648,
 51269,
 86047,
 1429,
 82718,
 50062,
 41268,
 58030,
 67934,
 59468,
 65751,
 74583,
 30953,
 35032,
 60223,
 76058,
 38520,
 66730,
 66748,
 84149,
 45654,
 66347,
 2211,
 82440,
 66933,
 60988,
 13049,
 42705,
 45127,
 17153,
 17200,
 79566,
 35555,
 55688,
 44447,
 44459,
 62102,
 29334,
 54284,
 36626,
 52781,
 77022,
 70574,
 70301,
 70308,
 35230,
 35452,
 49269,
 46845,
 73101,
 29033,
 53510,
 46970,
 48665,
 61991,
 47049,
 50278,
 51843,
 50758,
 74211,
 59574,
 60064,
 77586,
 48660,
 84616,
 61456,
 58606,
 18769,
 42118,
 85921,
 35646,
 42732,
 48599,
 83422,
 55978,
 49511,
 45563,
 84199,
 55356,
 55524,
 77136,
 77145,
 77152,
 37712,
 43544,
 48060,
 49505,
 46082,
 50706,
 38522,
 54094,
 66208,
 38645,
 68735,
 62515,
 62596,
 50680,
 45206,
 70529,
 73485,
 71891,
 46314,
 75181,
 84158,
 84844,
 45448,
 47011,
 43208,
 33963,
 77065,
 29911,
 56994,
 48096,
 63485,
 65137,
 30455,
 30477,
 38961,
 37067,
 52096,
 34051,
 21803,
 42186,
 58523,
 24687,
 38185,
 54462,
 53633,
 32871,
 53508,
 42537,
 42559,
 81546,
 59841,
 23600,
 52778,
 52907,
 40887,
 41379,
 61350,
 61571,
 61849,
 74432,
 74475,
 41757,
 71746,
 72387,
 72456,
 40770,
 40771,
 40787,
 32551,
 79583,
 44232,
 74606,
 2508,
 37392,
 51677,
 30070,
 62776,
 63589,
 66238,
 8261,
 8309,
 42523,
 44540,
 66633,
 36939,
 810,
 34329,
 50882,
 58345,
 68554,
 63884,
 75630,
 75645,
 71741,
 55139,
 58163,
 61132,
 1419,
 43604,
 25218,
 52915,
 22858,
 82067,
 46994,
 40071,
 56565,
 38261,
 63371,
 33690,
 43028,
 33242,
 33428,
 33502,
 77935,
 44729,
 73837,
 53679,
 56501,
 70966,
 38037,
 60274,
 50277,
 38781,
 42386,
 50410,
 53724,
 45485,
 59413,
 64800,
 56272,
 69732,
 3841,
 63825,
 50200,
 50259,
 45011,
 37918,
 43973,
 43626,
 51973,
 68114,
 55692,
 37979,
 60745,
 77420,
 79092,
 82878,
 37582,
 2948,
 54981,
 60633,
 35050,
 58914,
 58917,
 50919,
 56220,
 74581,
 61460,
 34355,
 33578,
 616,
 47903,
 51592,
 71807,
 50984,
 33831,
 46496,
 72192,
 71551,
 28105,
 38084,
 34437,
 74852,
 35515,
 43555,
 52948,
 60638,
 41274,
 6736,
 34813,
 71580,
 52674,
 34850,
 37888,
 47725,
 70793,
 53449,
 56569,
 55877,
 50586,
 51081,
 31659,
 81195,
 48924,
 67565,
 80170,
 53273,
 65422,
 35220,
 47689,
 39649,
 65282,
 62133,
 31995,
 3800,
 66074,
 60816,
 36015,
 82174,
 52892,
 1249,
 77005,
 37161,
 37319,
 62324,
 83746,
 61245,
 73022,
 41374,
 41561,
 78847,
 42433,
 73222,
 42986,
 48716,
 75091,
 35661,
 36968,
 42979,
 72819,
 74569,
 33787,
 39194,
 75064,
 651,
 44905,
 54093,
 85581,
 33654,
 33699,
 47749,
 48690,
 45598,
 82166,
 47358,
 43537,
 62423,
 62467,
 66806,
 38516,
 39799,
 54404,
 48526,
 48781,
 43822,
 29350,
 61534,
 46905,
 53667,
 38762,
 55301,
 50328,
 52874,
 73496,
 80248,
 84441,
 41943,
 29772,
 63602,
 83926,
 52942,
 47673,
 58044,
 46673,
 42305,
 41876,
 41884,
 57569,
 38126,
 44488,
 56074,
 39310,
 77222,
 64440,
 53919,
 48032,
 80643,
 25407,
 69877,
 75391,
 75513,
 29174,
 52088,
 79583,
 60867,
 73984,
 43035,
 41737,
 39269,
 22596,
 41610,
 70124,
 68006,
 33341,
 41098,
 50252,
 47355,
 54196,
 74277,
 60600,
 2892,
 41315,
 67488,
 4955,
 57447,
 35306,
 35338,
 49709,
 40789,
 65149,
 65155,
 9579,
 50986,
 46169,
 58680,
 58823,
 65661,
 72064,
 73433,
 1420,
 3826,
 47455,
 51481,
 59709,
 6236,
 70813,
 55438,
 81976,
 41766,
 59443,
 55194,
 57148,
 78081,
 49604,
 22080,
 53676,
 61075,
 30357,
 66744,
 51030,
 60370,
 56113,
 57553,
 36327,
 62669,
 47143,
 82587,
 3941,
 76186,
 76324,
 75516,
 33290,
 34333,
 32438,
 43936,
 61652,
 67659,
 67723,
 37893,
 66270,
 60363,
 60578,
 41077,
 58984,
 51780,
 51850,
 10336,
 23998,
 39403,
 74687,
 40374,
 40413,
 14952,
 69640,
 71907,
 69768,
 52345,
 56399,
 26990,
 39621,
 68237,
 40233,
 56779,
 25240,
 61997,
 42317,
 67572,
 48360,
 61294,
 65425,
 48111,
 68023,
 50650,
 40372,
 43063,
 43149,
 45223,
 46603,
 74405,
 86078,
 55358,
 4394,
 45060,
 27047,
 48207,
 57858,
 71311,
 55584,
 46529,
 5408,
 35499,
 55213,
 72898,
 60332,
 55432,
 13646,
 82432,
 72760,
 49071,
 53040,
 63187,
 51577,
 51633,
 43212,
 55303,
 43270,
 61420,
 72553,
 55792,
 50938,
 72998,
 40637,
 51142,
 38429,
 68091,
 68257,
 78447,
 29918,
 82933,
 38344,
 75016,
 13862,
 37081,
 50272,
 48211,
 36179,
 39900,
 76673,
 61183,
 41446,
 41831,
 59123,
 44862,
 82974,
 53390,
 58560,
 58668,
 40504,
 64546,
 60249,
 60450,
 56553,
 71909,
 72020,
 34928,
 76979,
 27970,
 61475,
 39906,
 58101,
 50119,
 39509,
 57989,
 68356,
 47056,
 85305,
 29672,
 60272,
 60346,
 60448,
 40052,
 59020,
 77729,
 52999,
 18653,
 84430,
 39953,
 39977,
 40479,
 40623,
 38015,
 38578,
 55036,
 77010,
 59925,
 49618,
 52452,
 76884,
 8676,
 79557,
 77327,
 64974,
 81324,
 65125,
 65281,
 31765,
 45988,
 71320,
 44237,
 37882,
 76225,
 38326,
 81729,
 2770,
 72125,
 72175,
 72200,
 612,
 15670,
 56317,
 50782,
 67016,
 56938,
 37792,
 46931,
 35673,
 62652,
 62678,
 45034,
 51921,
 52617,
 47654,
 68295,
 19185,
 19607,
 67690,
 36746,
 7204,
 56845,
 71646,
 1115,
 58949,
 36643,
 49573,
 43832,
 64544,
 64571,
 50138,
 50150,
 58583,
 35391,
 36613,
 55908,
 55920,
 54266,
 ...]

In [72]:
test_copy['timestamp']=a

In [73]:
test_copy

         id    ad  link  timestamp  grp  funnel_level
0      1728  2088   529      60951   98             0
1      3236   764   529      45400   98             0
2       818   811   529      73244   98             0
3      3344  2036   523      77553   11             0
4      3444  1246   523      56985   11             0
5      2765  1406   523      62170   11             0
6      3245  1560   523      69091   11             0
7      3317  1568   523      33910   11             0
8      1416  1561   523      78983   11             0
9       744  1724   523      54802   11             0
10     1281  1978   523      80115   11             0
11      901  1981   523      30327   11             0
12     1486  2117   523      57892   11             0
13      214  2121   523      40530   11             0
14     1472  2114   523      61784   11             0
15     2935  2418   523      38767   11             0
16     3056  2567   523      81688   11             0
17     2035  2565   523      46337   11             0
18     3335    59   523      44172   11             0
19     2917    68   523      46680   11             0
20     1215   352   523      61188   11             0
21     3411   351   523      44275   11             0
22      133   509   523      64442   11             0
23     1002   499   523      51900   11             0
24     2999   656   523      43960   11             0
25       70   791   523      57911   11             0
26     2933   964   523      35199   11             0
27     1434  1257   523      61433   11             0
28     2974  1267   523      65318   11             0
29      244  1285   523      34506   11             0
...     ...   ...   ...        ...  ...           ...
49384  1683   231  1844      30699   48             2
49385  2221   913  1840      49594    6             2
49386   581  1690  1841      58397    6             2
49387  2264   574  1839      73435    6             2
49388  1166  2472  1236      70552    1             1
49389  1166  2472  1236      70581    1             1
49390  3444  1246  1240      48127   39             1
49391  1469  1707  1240      47152   39             1
49392  1610  1516  1241      52512   40             1
49393   551  1733  1232      58461   59             1
49394   551  1733  1232      58461   41             1
49395  2137  1698  1242      34089   45             1
49396  2107  1904  1242      57048   45             1
49397  3199   450  1242      77130   45             1
49398   200   480  1242      54373   45             1
49399   200   480  1242      54374   45             1
49400   200   480  1242      54380   45             1
49401  2032   602  1242      41277   45             1
49402  3472   983  1242      44328   45             1
49403  1048  1589  1234      32729   74             2
49404  1776  2656  1234      48165   74             2
49405  1776  2656  1234      48179   74             2
49406  1213  2656  1234      56172   74             2
49407   107  2656  1233      37049   74             2
49408  1213  2656  1233      56175   74             2
49409  1522  2127  1235      70385   97             2
49410  1467  1512  1239      49931   27             2
49411  3225   429  1237      65231    7             2
49412  2445  2656  1238      48024   15             2
49413  2502  2097  1238      34204   15             2

[49414 rows x 6 columns]

In [74]:
test_copy.to_csv('test.csv',index=False)

In [79]:
Xt = [x for x in test_copy.columns if x not in ['order_placed','link','timestamp']]

In [169]:
pre_test=clf.predict(test_copy[X])

In [170]:
test=pd.read_csv('test_data .csv')
sub=pd.DataFrame()
sub['id']=test['id']
sub['order_placed']=pre_test

In [171]:
sub.to_csv('submission.csv',index=False)

In [ ]:
sub

In [ ]:
clf.feature_importances_

In [ ]:
sel = VarianceThreshold(threshold=(.8 * (1 - .8)))
sel.fit_transform(train_copy[X])

In [ ]:
train_copy

In [ ]:
# feature extraction
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(train_copy[X], y)
# summarize scores
np.set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(train_copy[X])
# summarize selected features
print(features[0:5,:])

In [ ]:
model = ExtraTreesClassifier()
model.fit(train_copy[X],y)
print(model.feature_importances_)

In [ ]:
clf.get_params(deep=True)

In [ ]:
clf.predict_proba(train[X])